#!/usr/bin/bash

meeu=$(whoami)
meui=$(id -u)
megi=$(id -g)
pfpd='2001:8a0:fcdd:d00'
cunm=$(hostname)
cuip=$(hostname -I);cuip=${cuip%% *}
vip1='51.89.64.77' ;vnd1='ns31198432.ip-51-89-64.eu'   ;vnm1=${vnd1%%.*};vis1='127.0.0.1'
vip2='51.89.64.205';vnd2='ns3168040.ip-51-89-64.eu'    ;vnm2=${vnd2%%.*};vis2='127.0.0.1'
vip3='161.97.85.32';vnd3='vmi1007895.contaboserver.net';vnm3=${vnd3%%.*};vis3='127.0.0.1'
mrpd='/mnt/bkp'
trmd='/mnt/downloads'
mdld='/media/mp4'
dkcr="/opt"
dkcn='arrdata'
dkcd="$dkcr/$dkcn"
dkcc="/home/$meeu/arr/docker-compose.yml"

function sit { ! [[ $1 =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]; }
function sht { [[ ${1:-$cuip} = 192.168.8.* ]]; }
function snt { [[ $1 = hrv* ]]; }
function smt { sht "$1" || snt "$1"; }
function snu { local s=$1;[[ "$s" = "192.168.8.25" || "$s" = hrv-zotac1* || "$s" = hrv-protectli* ]] && s="admin@$s";printf %s "$s"; }
function sin {
  local s=$1
  case $1 in
  hrv-protectli*) s=192.168.8.25 ;;
  hrv-zotac1*) s=192.168.8.25 ;;
  hrv-zotac2*) s=192.168.8.28 ;;
  hrv-zotac3*) s=192.168.8.31 ;;
  hrv-zotac4*) s=192.168.8.34 ;;
  hrv-intel5*) s=192.168.8.37 ;;
  hrv-intel6*) s=192.168.8.40 ;;
  hrv-zen*   ) s=192.168.8.100 ;;
  hrv-lenovo*) s=192.168.8.101 ;;
  $vnm1*) s=$vip1 ;;
  $vnm2*) s=$vip2 ;;
  $vnm3*) s=$vip3 ;;
  $vnd1*) s=$vip1 ;;
  $vnd2*) s=$vip2 ;;
  $vnd3*) s=$vip3 ;;
  esac
  printf %s "$s"
 }
function snd {
  case $1 in
  $vnm1) printf $vnd1 ;;
  $vnm2) printf $vnd2 ;;
  $vnm3) printf $vnd3 ;;
  *) printf %s "$1" ;;
  esac
}
function si6 {
  case $1 in
  hrv-protectli*) printf %s $pfpd:6662:66ff:fe22:9688 ;;
  hrv-zotac1*) printf %s $pfpd:201:2eff:fea0:88d4 ;;
  hrv-zotac2*) printf %s $pfpd::1002 ;;
  hrv-zotac3*) printf %s $pfpd::1003 ;;
  hrv-zotac4*) printf %s $pfpd::1004 ;;
  hrv-intel5*) printf %s $pfpd::1005 ;;
  hrv-intel6*) printf %s $pfpd::1006 ;;
  hrv-zen*   ) printf %s $pfpd::1100 ;;
  hrv-lenovo*) printf %s $pfpd::1101 ;;
  *) printf %s "$1" ;;
  esac
}
function sl6 {
  case $1 in
  hrv-protectli*) printf %s fe80::6662:66ff:fe22:9688 ;;
  hrv-zotac1*) printf %s fe80::201:2eff:fea0:88d4 ;;
  hrv-zotac2*) printf %s fe80::201:2eff:fea0:e06f ;;
  hrv-zotac3*) printf %s fe80::201:2eff:fea0:88ea ;;
  hrv-zotac4*) printf %s fe80::201:2eff:fea4:f04c ;;
  hrv-intel5*) printf %s fe80::4a21:bff:fe55:4076 ;;
  hrv-intel6*) printf %s fe80::4a21:bff:fe52:6c5e ;;
  hrv-zen*   ) printf %s fe80::9fa6:2019:3db8:d1b6 ;;
  hrv-lenovo*) printf %s fe80::c988:b438:1645:2e90 ;;
  *) printf %s "$1" ;;
  esac
}
function spn {
  local s=${1##*@};sit $s && local s=${1%%.*}
  local n=2020
  case $s in
  hrv-protectli*) n=2021 ;;
  hrv-zotac1*) n=2021 ;;
  hrv-zotac2*) n=2022 ;;
  hrv-zotac3*) n=2023 ;;
  hrv-zotac4*) n=2024 ;;
  hrv-intel5*) n=2025 ;;
  hrv-intel6*) n=2026 ;;
  192.168.8.25) n=2021 ;;
  192.168.8.28) n=2022 ;;
  192.168.8.31) n=2023 ;;
  192.168.8.34) n=2024 ;;
  192.168.8.37) n=2025 ;;
  192.168.8.40) n=2026 ;;
  esac
  printf %i $n
}
function sio {
  local i=111
  case $1 in
  2021) i=25 ;;
  2022) i=28 ;;
  2023) i=31 ;;
  2024) i=34 ;;
  2025) i=37 ;;
  2026) i=40 ;;
  esac
  printf %i $i
 }
function sns {
  local s=$1
  if [[ ${#1} -eq 2 ]]; then
    if [[ ${1:0:1} = z ]]; then
      if [[ ${1:1:1} -le 4 ]]; then
        s=${1/z/hrv-zotac}
      else
        s=${1/z/hrv-intel}
      fi
    else
      case $1 in
      v1) s=$vnd1 ;;
      v2) s=$vnd2 ;;
      v3) s=$vnd3 ;;
       *) s=$1 ;;
      esac
    fi
  fi
  snu $(sin "$s")
}
function stt { [[ $cut1 != $cut2 ]]; }
function sxt { [[ $cunm = $cut1 || $cunm = $cut2 ]]; }
function sst { local s=${1:-$cunm};[[ $s != hrv-zen && $s != hrv-lenovo ]]; }
function msh { 
  if [[ $# -lt 1 ]];then 
    echo -e "msh [user@]{server} [port] [command]\t\tssh -4p <port> <server> '<command>'"
    return
  fi
  local s;local p;local e;local i;local u;local w
  while [[ $# -gt 0 ]];do i=$(sns "${1#*@}");[[ "$1" == *'@'* ]] && u=${1%@*};[[ $u ]] || if [[ "$i" == *'@'* ]];then u=${i%@*};fi
      if [[ "$1" =~ ^[0-9]+$ ]]; then
        p=$1
      elif [[ "$1" == -q ]]; then
        w=no
      elif sit "${i#*@}"; then
        e="$1";[[ $w = no ]] || w=''
      else
       [[ $u ]] && u=$u@;s="$u${i#*@}";[[ $p ]] || p=$(spn $s)
      fi
      shift
  done
  [[ $w ]] || echo ssh -4p $p $s $e;ssh -4p $p $s "$e"
}
function mcp {
  if [[ $# -lt 1 ]];then 
    echo -e "mcp [port] {zv}{123456}:{file|dir} [d:~]\t\tscp -4rP <port> <server>:{file|dir} <destination>"
    echo -e "mcp [port] {file|dir} {zv}{123456}:[d:~]\t\tscp -4rP <port> {file|dir} <server>:<destination>"
    return
  fi
  local a=();local s;local f;local p;local w
  while [[ $# -gt 0 ]];do s="$1"
      if [[ "$s" == *:* ]] && [[ "$s" != -* ]] && [[ ! "$s" =~ ^(\.|/) ]]; then
        f=${s##*:};s=$(sns "${s%:*}");[[ $p ]] || p=$(spn "${s%:*}");a+=("$s:$f")
      elif [[ "$s" == -q ]]; then
        w=no
      elif [[ "$s" =~ ^[0-9]+$ ]]; then
        p=$s
      else
        a+=("$s")
      fi
      shift
  done
  [[ $w ]] || echo scp -4rP $p ${a[@]};scp -4rP $p "${a[@]}"
}
function pcm { 
  local e=${1^^};local s=hrv-protectli;local m='eth2/rt-GR241AG'
  if   [[ $e = PRB  ]];then msh -q $s "/etc/rc.reboot"
  elif [[ $e = NTP  ]];then msh -q $s "ntpq -np"
  elif [[ $e = IP4  ]];then msh -q $s "ifconfig igc0|grep inet |grep -v inet6|awk '{print \$2}'"
  elif [[ $e = IP6  ]];then msh -q $s "ifconfig igc1|grep inet6|grep -v fe80 |awk '{print \$2}'"
  elif [[ $e = SYL  ]];then msh -q $s "/root/rt-pfsense-log-check.sh $(date +%H)"
  elif [[ $e = LOGS ]];then echo;if [[ -f ~/$m ]]; then echo meo reboot log;tail -n5 ~/$m;fi;msh -q $s "/root/rt-pfsense-log-check.sh $2"
  elif [[ $e = DHCP ]];then msh -q $s "/root/rt-pfsense-log-check.sh dhcpd $2"
  else                      msh -q $s "cat /root/wan-check.log"
  fi
}
function san { local s=${1:-UP};ip -j addr|jq -r ".[]|select(.operstate==\"${s^^}\").ifname"|grep '^en'; }
function sa6 { local s=${1:-UP};ip -j addr|jq -r ".[]|select(.operstate==\"${s^^}\").addr_info.[]|select(.family==\"inet6\" and .scope==\"global\").local"; }
function ufz { echo "$B"|gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 -c $1; }
function zfu { echo "$B"|gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 -d $1 2>/dev/null; }
