#!/usr/bin/bash

meeu=$(whoami)
meui=$(id -u)
megi=$(id -g)
pfpd='2001:8a0:fcd9:4500'
cunm=$(hostname)
cuip=$(hostname -I);cuip=${cuip%% *}
vip1='51.89.64.77' ;vnd1='ns31198432.ip-51-89-64.eu'   ;vnm1=${vnd1%%.*};vis1='127.0.0.1'
vip2='51.89.64.205';vnd2='ns3168040.ip-51-89-64.eu'    ;vnm2=${vnd2%%.*};vis2='127.0.0.1'
vip3='161.97.85.32';vnd3='vmi1007895.contaboserver.net';vnm3=${vnd3%%.*};vis3='127.0.0.1'
mrpd='/mnt/bkp'
trmd='/mnt/downloads'
mdld='/media/mp4'
dkcr="/opt"
dkcn='arrdata'
dkcd="$dkcr/$dkcn"
dkcc="/home/$meeu/arr/docker-compose.yml"
netv='1.39.2';netc='65689105'
ligv='v8.2.1'
mevv='v1.12'
golv='go1.26.4'
sdcv='v2.8.0';sdcc='948d3fc'
edcv='v1.2.0';edcc='18b7608'
edov='1.39.0'
getv='1.13.14';getc='2bd6bd01'
bsuv='23.1.0'
om00='function par(h) {v=strtonum(h);if (v>32767) {v-=65536};return v*0.002}'
om01="{print}"
om02="$om00;\$1 == \"NumOfTcont:\"                  {printf \"%-35s           MEO %i Upstream Bandwidth Containers (T-CONTs)\n\", \$0, \$2;next}"
om02="$om02;\$1 == \"OpticalSignalLevel:\"          {printf \"%-34s %6.2f dBm MEO (-8.0/-27.0 dBm)\n\", \$0, par(\$2);next}"
om02="$om02;\$1 == \"TranOpticLevel:\"              {printf \"%-34s %6.2f dBm MEO (+0.5/ +5.0 dBm)\n\", \$0, par(\$2);next}"
om02="$om02;\$1 == \"OntRspTime:\"                  {printf \"%-35s           MEO Internal logical distance/ranging delay calculated by the OLT %i bits\n\", \$0, \$2;next}"
om03="\$2 == \"0xffff\"                             {printf \"%-35s           MEO VEIP / Virtual Ethernet Interface Point\n\", \$0;next}"
om03="$om03;\$5 == \"VID\" && \$6 == 12             {printf \"%-35s           MEO Internet\n\", \$0;next}"
om03="$om03;\$5 == \"VID\" && \$6 == 528            {printf \"%-35s           MEO TR-069 Remote Management\n\", \$0;next}"
om04="\$1 == \"Timestamp:\"                         {printf \"%-38.38s MEO hardware-level Time of Day (ToD) synchronization\n\", \$0;next}"
om04="$om04;\$1 == \"OltVendorId:\"                 {printf \"%-35s           MEO %4s=PT Inovação, which is the former name of Altice Labs\n\", \$0, \$2;next}"
om05="\$1 == \"Version:\"                           {printf \"%-35s           MEO GR241AG Software Version %s\n\", \$0, \$2;next}"
om06="\$1 == \"Version:\"                           {printf \"%-35s           MEO Hardware Version %s\n\", \$0, \$2;next}"
om06="$om06;\$1 == \"SerialNum:\"                   {printf \"%-35s           MEO GPON Serial Number %s\n\", \$0, \$2;next}"
om06="$om06;\$1 == \"VID:\"                         {printf \"%-35s           MEO Vendor ID %s\n\", \$0, \$2;next}"
om06="$om06;\$1 == \"TraffMgtOpt:\" && \$2 == 0     {printf \"%-35s           MEO uses Priority-controlled multiplexing\n\", \$0;next}"
om06="$om06;\$1 == \"TraffMgtOpt:\" && \$2 == 1     {printf \"%-35s           MEO uses Rate-controlled multiplexing\n\", \$0;next}"
om06="$om06;\$1 == \"OntState:\"                    {printf \"%-35s           MEO OMCI stack %i (1 ONT state machine has achieved full synchronization with the OLT)\n\", \$0, \$2;next}"
om06="$om06;\$1 == \"AdminState:\"                  {printf \"%-35s           MEO OMCI stack %i (0 OMCI Management path is fully unlocked)\n\", \$0, \$2;next}"
om06="$om06;\$1 == \"OpState:\"                     {printf \"%-35s           MEO OMCI stack %i (0 administratively enabled)\n\", \$0, \$2;next}"
om07="\$2 == \"0xffff\"                             {printf \"%-35s           MEO VEIP / Virtual Ethernet Interface Point\n\", \$0;next}"
om07="$om07;\$1 == \"NumOfAllowedMac:\"             {printf \"%-35s           MEO Allowed MAC limit %i (0 Unlimited / No Limit enforced)\n\", \$0, \$2;next}"
om07="$om07;\$1 == \"PortNum:\" && \$2 == 4         {printf \"%-35s           MEO (4 Internet, VoIP, IPTV, Mgmt)\n\", \$0;next}"
om07="$om07;\$1 == \"MaxLearningAddresses:\"        {printf \"%-35s           MEO %i MAC addresses behind the ONT (0 the OLT is perfectly fine with seeing multiple MAC addresses)\n\", \$0, \$2;next}"
om08="\$1 == \"AdminState:\"                        {printf \"%-35s           MEO %i (0 Unlocked/Enabled) \n\", \$0, \$2;next}"
om08="$om08;\$1 == \"OpState:\"                     {printf \"%-35s           MEO %i (0 Active) \n\", \$0, \$2;next}"
om08="$om08;\$1 == \"PauseTime:\"                   {printf \"%-35s           MEO pause-frame timer of %i (0 disabled)\n\", \$0, \$2;next}"
om08="$om08;\$1 == \"MaxFrameSize:\"                {printf \"%-35s           MEO MTU ceiling of %i bytes (supporting baby jumbo frames / VLAN overhead)\n\", \$0, \$2;next}"
om09="\$1 == \"CIR:\"                               {printf \"%-35s           MEO Commited Information Rate %i upstream traffic hard limits\n\", \$0, \$2;next}"
om09="$om09;\$1 == \"PIR:\"                         {printf \"%-35s           MEO Peak Information Rate %i upstream traffic hard limits\n\", \$0, \$2;next}"
om09="$om09;\$1 == \"AllocId:\"                     {printf \"%-35s           MEO Allocation ID %i\n\", \$0, \$2;next}"
om09="$om09;\$1 == \"TrafficDescriptor\"            {printf \"%-35s           MEO If CIR=0, PIR=0, the upload limit is managed at the OLT layer via DBA (Dynamic Bandwidth Allocation)\n\", \$0;next}"

function sit { ! [[ $1 =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]; }
function sht { [[ ${1:-$cuip} = 192.168.8.* ]]; }
function snt { [[ $1 = hrv* ]]; }
function smt { sht "$1" || snt "$1"; }
function snu { local s=$1;[[ "$s" = "192.168.8.25" || "$s" = hrv-zotac1* || "$s" = hrv-protectli* ]] && s="admin@$s";printf %s "$s"; }
function sin {
  local s=$1
  case $1 in
  hrv-protectli*) s=192.168.8.25 ;;
  hrv-zotac1*) s=192.168.8.25 ;;
  hrv-zotac2*) s=192.168.8.28 ;;
  hrv-zotac3*) s=192.168.8.31 ;;
  hrv-zotac4*) s=192.168.8.34 ;;
  hrv-intel5*) s=192.168.8.37 ;;
  hrv-intel6*) s=192.168.8.40 ;;
  hrv-zen*   ) s=192.168.8.100 ;;
  hrv-lenovo*) s=192.168.8.101 ;;
  $vnm1*) s=$vip1 ;;
  $vnm2*) s=$vip2 ;;
  $vnm3*) s=$vip3 ;;
  $vnd1*) s=$vip1 ;;
  $vnd2*) s=$vip2 ;;
  $vnd3*) s=$vip3 ;;
  esac
  printf %s "$s"
 }
function snd {
  case $1 in
  $vnm1) printf $vnd1 ;;
  $vnm2) printf $vnd2 ;;
  $vnm3) printf $vnd3 ;;
  *) printf %s "$1" ;;
  esac
}
function si6 {
  case $1 in
  hrv-protectli*) printf %s $pfpd:6662:66ff:fe22:9688 ;;
  hrv-zotac1*) printf %s $pfpd:201:2eff:fea0:88d4 ;;
  hrv-zotac2*) printf %s $pfpd::1002 ;;
  hrv-zotac3*) printf %s $pfpd::1003 ;;
  hrv-zotac4*) printf %s $pfpd::1004 ;;
  hrv-intel5*) printf %s $pfpd::1005 ;;
  hrv-intel6*) printf %s $pfpd::1006 ;;
  hrv-zen*   ) printf %s $pfpd::1100 ;;
  hrv-lenovo*) printf %s $pfpd::1101 ;;
  *) printf %s "$1" ;;
  esac
}
function sl6 {
  case $1 in
  hrv-protectli*) printf %s fe80::6662:66ff:fe22:9688 ;;
  hrv-zotac1*) printf %s fe80::201:2eff:fea0:88d4 ;;
  hrv-zotac2*) printf %s fe80::201:2eff:fea0:e06f ;;
  hrv-zotac3*) printf %s fe80::201:2eff:fea0:88ea ;;
  hrv-zotac4*) printf %s fe80::201:2eff:fea4:f04c ;;
  hrv-intel5*) printf %s fe80::4a21:bff:fe55:4076 ;;
  hrv-intel6*) printf %s fe80::4a21:bff:fe52:6c5e ;;
  hrv-zen*   ) printf %s fe80::9fa6:2019:3db8:d1b6 ;;
  hrv-lenovo*) printf %s fe80::c988:b438:1645:2e90 ;;
  *) printf %s "$1" ;;
  esac
}
function spn {
  local s=${1##*@};sit $s && local s=${1%%.*}
  local n=2020
  case $s in
  hrv-protectli*) n=2021 ;;
  hrv-zotac1*) n=2021 ;;
  hrv-zotac2*) n=2022 ;;
  hrv-zotac3*) n=2023 ;;
  hrv-zotac4*) n=2024 ;;
  hrv-intel5*) n=2025 ;;
  hrv-intel6*) n=2026 ;;
  192.168.8.25) n=2021 ;;
  192.168.8.28) n=2022 ;;
  192.168.8.31) n=2023 ;;
  192.168.8.34) n=2024 ;;
  192.168.8.37) n=2025 ;;
  192.168.8.40) n=2026 ;;
  esac
  printf %i $n
}
function sio {
  local i=122
  case $1 in
  2021) i=25 ;;
  2022) i=28 ;;
  2023) i=31 ;;
  2024) i=34 ;;
  2025) i=37 ;;
  2026) i=40 ;;
  esac
  printf %i $i
 }
function sns {
  local s=$1
  if [[ ${#1} -eq 2 ]]; then
    if [[ ${1:0:1} = z ]]; then
      if [[ ${1:1:1} -le 4 ]]; then
        s=${1/z/hrv-zotac}
      else
        s=${1/z/hrv-intel}
      fi
    else
      case $1 in
      v1) s=$vnd1 ;;
      v2) s=$vnd2 ;;
      v3) s=$vnd3 ;;
       *) s=$1 ;;
      esac
    fi
  fi
  snu $(sin "$s")
}
function stt { [[ $cut1 != $cut2 ]]; }
function sxt { [[ $cunm = $cut1 || $cunm = $cut2 ]]; }
function sst { local s=${1:-$cunm};[[ $s != hrv-zen && $s != hrv-lenovo ]]; }
function msh { 
  if [[ $# -lt 1 ]];then 
    echo -e "msh [user@]{server} [port] [command]\t\tssh -4p <port> <server> '<command>'"
    return
  fi
  local s;local p;local e;local i;local u;local w
  while [[ $# -gt 0 ]];do i=$(sns "${1#*@}");[[ "$1" == *'@'* ]] && u=${1%@*};[[ $u ]] || if [[ "$i" == *'@'* ]];then u=${i%@*};fi
      if [[ "$1" =~ ^[0-9]+$ ]]; then
        p=$1
      elif [[ "$1" == -q ]]; then
        w=no
      elif sit "${i#*@}"; then
        e="$1";[[ $w = no ]] || w=''
      else
       [[ $u ]] && u=$u@;s="$u${i#*@}";[[ $p ]] || p=$(spn $s)
      fi
      shift
  done
  [[ $w ]] || echo ssh -4p $p $s $e;ssh -4p $p $s "$e" 2>/dev/null
}
function mcp {
  if [[ $# -lt 1 ]];then 
    echo -e "mcp [port] {zv}{123456}:{file|dir} [d:~]\t\tscp -4rP <port> <server>:{file|dir} <destination>"
    echo -e "mcp [port] {file|dir} {zv}{123456}:[d:~]\t\tscp -4rP <port> {file|dir} <server>:<destination>"
    return
  fi
  local a=();local s;local f;local p;local w
  while [[ $# -gt 0 ]];do s="$1"
      if [[ "$s" == *:* ]] && [[ "$s" != -* ]] && [[ ! "$s" =~ ^(\.|/) ]]; then
        f=${s##*:};s=$(sns "${s%:*}");[[ $p ]] || p=$(spn "${s%:*}");a+=("$s:$f")
      elif [[ "$s" == -q ]]; then
        w=no
      elif [[ "$s" =~ ^[0-9]+$ ]]; then
        p=$s
      else
        a+=("$s")
      fi
      shift
  done
  [[ $w ]] || echo scp -4rP $p ${a[@]};scp -4rP $p "${a[@]}" 2>/dev/null
}
function leh { echo -e "leo <param>\nLEORB\treboot\nlog\tdmesg\nxml\tconfig\nos\tOptical Signal\nvl\tVLANs\nmac\tMAC Bridge Configuration Data\nuni\tPhysical Path Termination Point Ethernet UNI\ntd\tTraffic Descriptor\nolt\tOLT revealing its own identity\nver\tSoftware is currently running\nont\tONT revealing its own identity\npon\tGPON State Machine\nupt\tUptime"; }
function ltl { expect -c "spawn telnet 192.168.100.1;expect \"ogin:\";send \"leox\r\";expect \"assword:\";send \"$V\r\";expect \"#\";send \"$*\r\";expect \"$*\";expect \"#\";send \"exit\r\";expect eof"; }
function leo { 
  if   [[ $1 = LEORB ]];then ltl reboot
  elif [[ $1 = log   ]];then ltl dmesg
  elif [[ $1 = xml   ]];then ltl flash all
  elif [[ $1 = os    ]];then ltl omcicli mib get 263 | tr -d '\r' | awk "$om02;$om01"
  elif [[ $1 = vl    ]];then ltl omcicli mib get 84  | tr -d '\r' | awk "$om03;$om01"
  elif [[ $1 = mac   ]];then ltl omcicli mib get 47  | tr -d '\r' | awk "$om07;$om01"
  elif [[ $1 = uni   ]];then ltl omcicli mib get 11  | tr -d '\r' | awk "$om08;$om01"
  elif [[ $1 = td    ]];then ltl omcicli mib get 280 | tr -d '\r' | awk "$om09;$om01"
  elif [[ $1 = olt   ]];then ltl omcicli mib get 131 | tr -d '\r' | awk "$om04;$om01"
  elif [[ $1 = ver   ]];then ltl omcicli mib get 7   | tr -d '\r' | awk "$om05;$om01"
  elif [[ $1 = ont   ]];then ltl omcicli mib get 256 | tr -d '\r' | awk "$om06;$om01"
  elif [[ $1 = pon   ]];then ltl diag gpon get onu-state
  elif [[ $1 = upt   ]];then ltl uptime -p
  else leh
  fi
}
function pfh { echo -e "pfs <param> [hours]\nPFSRB\t\tpfSense reboot\nfw[qsl]\t\tFirewall show Queues/Schedulers/Limiters\nip{46crd}\tshow ip4/ip6/config/route/discovery\ndsk\t\tshow disk usage\ndhcpc?6?\tpfSense logs dhcp[client]\ndns\t\tresolver\ngw\t\tgateways\nlogs?\t\tsystem[dhcp]\nlst\t\tlink-state"; }
function pfs { 
  local s=hrv-protectli;local i=${1:0:2};local r=${1:2}
  if   [[ $1 = PFSRB ]];then msh -q $s "/etc/rc.reboot"
  elif [[ $i = fw    ]];then shift;if [[ $r = q ]];then i=queue;elif [[ $r = l ]];then i=pipe;else i=sched;fi;i="ipfw $i show";[[ $# -gt 0 ]] && i="$i 0$(printf ',%i' $@)";echo "$i";msh -q $s "$i"
  elif [[ $i = ip    ]];then msh -q $s "/root/rt-pfsense-ip.sh $1"
  elif [[ $1 = dsk   ]];then msh -q $s "smartctl -a /dev/ada0|grep -E 'Model:|^ID#|^ *(5|9|187) +[A-Z]'"
  elif [[ $1 = dns   ]];then msh -q $s "/root/rt-pfsense-log-check.sh resolver ${2:-24}"
  elif [[ $1 = gw    ]];then msh -q $s "/root/rt-pfsense-log-check.sh gateways ${2:-24}"
  elif [[ $1 = dhcp || $1 = dhcp6 || $1 = dhcpc || $1 = dhcpc6 || $1 = log || $1 = logs || $1 = lst ]];then msh -q $s "/root/rt-pfsense-log-check.sh $1 ${2:-24}"
  else pfh
  fi
}
function san { local s=${1:-UP};ip -j addr|jq -r ".[]|select(.operstate==\"${s^^}\").ifname"|grep '^en'; }
function sa6 { local s=${1:-UP};ip -j addr|jq -r ".[]|select(.operstate==\"${s^^}\").addr_info.[]|select(.family==\"inet6\" and .scope==\"global\").local"; }
function ufz { echo "$B"|gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 -c $1; }
function zfu { echo "$B"|gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 -d $1 2>/dev/null; }
