#!/usr/bin/bash

function sin {
  case $1 in
  hrv-zotac1*) printf 192.168.8.25 ;;
  hrv-zotac2*) printf 192.168.8.28 ;;
  hrv-zotac3*) printf 192.168.8.31 ;;
  hrv-zotac4*) printf 192.168.8.34 ;;
  hrv-intel5*) printf 192.168.8.37 ;;
  hrv-intel6*) printf 192.168.8.40 ;;
  hrv-zen*   ) printf 192.168.8.100 ;;
  hrv-lenovo*) printf 192.168.8.101 ;;
  *) printf %s "$1" ;;
  esac
}
function spn {
  local n=2020
  local s=${1%%.*}
  case $1 in
  hrv*) n=$((n+${s##*[!0-9]})) ;;
  192.168.8.25) n=2021 ;;
  192.168.8.28) n=2022 ;;
  192.168.8.31) n=2023 ;;
  192.168.8.34) n=2024 ;;
  192.168.8.37) n=2025 ;;
  192.168.8.40) n=2026 ;;
  esac
  printf %i $n
}
function sht { [[ $(hostname -I|cut -d. -f1-3) = 192.168.8 ]]; }
function sot { nslookup "$1" 2>/dev/null 1>&2; }
function sit { [[ $1 = 192.168.8.* ]]; }
function snt { [[ $1 = hrv* ]]; }
function sdt { sit "$1" || snt "$1"; }
function srt { [[ $1 = 192.168.8.25 || $1 = hrv-zotac1* ]]; }
function dnn { local s=$1;snt "$s" && ! sht && s="$s.fruga.pt";sot "$s" || s=$(sin "$1");srt "$s" && s="admin@$s";printf %s "$s"; }
function dnz { local p=$2;[[ $p ]] || p=$(spn "$1");printf %i "$p"; }
function zsh { ssh -p "$1" -i ~/.ssh/id_ed25519 "$2" "$3"; }
function zcp { local p=$1;local d=$2;shift;shift;scp -rP "$p" -i ~/.ssh/id_ed25519 $@ "$d"; }
function pcm { 
  local n;local p;local s=hrv-zotac1;n=$(dnn $s);p=$(dnz $s)
  if [[ $1 = RB ]];then 
    zsh "$p" "$n" "/etc/rc.reboot"
  elif [[ $1 = NTP ]];then 
    zsh "$p" "$n" "ntpq -p"
  else 
    zsh "$p" "$n" 'tail -n20 /root/rt-pfsense-wan-check.log'
  fi
}
function tcm {
  local s=hrv-zotac1;echo -e "\n\e[32m$s pfSense\e[0m";pcm NTP
  s=hrv-zotac2;echo -e "\n\e[32m$s chronyc\e[0m";zsh $(dnz $s) $(dnn $s) "chronyc sources"
}