#!/usr/bin/bash

source /home/eth/eth2/a0

function msh { echo -e "\n\e[5;32m${*^^}\e[0m";eval "$*"; }
# function icm { dig +domain=unknown.home.arpa AAAA "$@";dig +domain=home.arpa AAAA "$@";dig +domain=unknown.home.arpa A "$@";dig +domain=home.arpa A "$@"; }
# function dsh { msh resolvectl flush-caches;icm hrv-zotac1 hrv-zotac2 hrv-zotac3 hrv-zotac4 hrv-intel5 hrv-intel6 hrv-zen hrv-lenovo lgwebostv lgwebostv0 dreamevacuumr2364a pixel-9-pro-xl|grep -E '^[a-z]{3}'|sort; }
function esl { local p;local s;p=$(dnz "$1" "$2");s=$(dnn "$1");echo -e "\nssh -4p $p $s:";zsh "$p" "$s"; }
function erq { local q=${*:-changelogs.ubuntu.com};msh resolvectl query "$q"; }

alias rr='pcm PRB'
alias rt='tcm'
alias rl='pcm LRB'

alias z1='esl hrv-zotac1'
alias z2="esl hrv-zotac2"
alias z3="esl hrv-zotac3"
alias z4="esl hrv-zotac4"
alias z5="esl hrv-intel5"
alias z6="esl hrv-intel6"

alias ky='ssh-keygen -f ~/.ssh/id_ed25519 -t ed25519 -C "$(whoami)@$(hostname)";cat ~/.ssh/id_ed25519.pub'
alias rq='msh "ip a s $(slk);ip r;ip -6 r";systemctl is-active --quiet systemd-networkd && msh networkctl status;msh resolvectl status $(slk);erq github.com changelogs.ubuntu.com'
alias xx='exit'
