#!/usr/bin/bash

cunm=$(hostname)
cust=${cunm:0:3}
function sht { [[ $cust = hrv ]]; }
function dnn { local s=$1;[[ ${s%%.*} =~ ^[a-zA-Z]+ ]] && ! sht && s="$s.fruga.pt";[[ ${s%%.*} == hrv-zotac1 ]] && s="admin@$s";printf %s $s; }
function dnp { local n=${1##*[!0-9]};local p=2020;[[ $1 =~ ^hrv-[a-z]{5}[0-9]$ ]] && p=$((p+n));printf %i $p; }
function dnz { local p=$2;[[ $p ]] || p=$(dnp $1);printf %i $p; }
function zsh { ssh -p $1 -i ~/.ssh/id_ed25519 $2 "$3"; }

function msh { echo -e "\n\e[5;32m${*^^}\e[0m";eval "$*"; }
function dsh {
  resolvectl flush-caches
 (msh dig AAAA hrv-zotac1.home.arpa;msh dig AAAA hrv-zotac1.unknown.home.arpa
  msh dig AAAA hrv-zotac2.home.arpa;msh dig AAAA hrv-zotac2.unknown.home.arpa
  msh dig AAAA hrv-zotac3.home.arpa;msh dig AAAA hrv-zotac3.unknown.home.arpa
  msh dig AAAA hrv-zotac4.home.arpa;msh dig AAAA hrv-zotac4.unknown.home.arpa
  msh dig AAAA hrv-intel5.home.arpa;msh dig AAAA hrv-intel5.unknown.home.arpa
  msh dig AAAA hrv-intel6.home.arpa;msh dig AAAA hrv-intel6.unknown.home.arpa
  msh dig AAAA hrv-zen.home.arpa;msh dig AAAA hrv-zen.unknown.home.arpa
  msh dig AAAA hrv-lenovo.home.arpaS;msh dig AAAA hrv-lenovo.unknown.home.arpaS
  msh dig AAAA hrv-lgwebostv.home.arpa;msh dig AAAA hrv-lgwebostv.unknown.home.arpa
  msh dig AAAA hrv-pixel-9-pro-xl.home.arpa;msh dig AAAA hrv-pixel-9-pro-xl.unknown.home.arpa
  )|grep AAAA|grep '^hrv-'
}
function esl { local p=$(dnz $1 $2);local s=$(dnn $1);echo -e "\nzsh $s:$p     ";zsh $p $s; }
function erq { local q=${1:-github.com};msh resolvectl query $q; }
function nrs { sudo netplan apply;sudo systemctl stop systemd-resolved;sleep 9;sudo systemctl start systemd-resolved;sleep 9;resolvectl status; }

function zcp { local p=$1;local d=$2;shift;shift;scp -P $p -i ~/.ssh/id_ed25519 $@ "$d"; }
function ecp { local p=$(dnz $1 $2);local s=$(dnn $1);echo -e "\nzcp $s:$p eth2";cc2 $1 $p; }
function ocp { local p=$(dnz $1 $2);local s=$(dnn $1);echo -e "\nzcp $s:$p ocp ";cc1 $1 $p;zcp $p $s:~/.ssh/authorized_keys ~/eth2/keth; }
function ccp { local p=$(dnz $1 $2);local s=$(dnn $1);echo -e "\nzcp $s:$p ccp ";zcp $p $s: ~/eth2/cns.keys.gpg;zcp $p $s: ~/eth2/hernanirvaz-f2e8fb66dbc0.json.gpg; }
function rcp { local p=$(dnz $1 $2);local s=$(dnn $1);echo -e "\nzcp $s:$p rcp ";zcp $p $s:~/.ssh/authorized_keys ~/eth2/keth;zcp $p $s: ~/eth2/rt-pfsense-wan-check.sh; }
function cc1 { zcp $2 $(dnn $1):~/.bash_aliases ~/eth2/asrv            ; }
function cc2 { zcp $2 $(dnn $1):~/eth2          ~/eth2/t[1-9] ~/eth2/e?; }
function ecv { local s='';for s in $@;do ecp $s;done; }
function ocv { local s='';for s in $@;do ocp $s;done; }
function ei0 { echo -e "export H=\"$1\"\nexport E=\"$2\"\nexport R=\"$3\"\nexport V=\"$4\"\npr=$5"; }
function ei1 { echo -e "echo>>~/.bashrc\necho \"export PATH=\\\"\\\$PATH:/home/eth/eth2\\\"\">>~/.bashrc\necho \"export H=\\\"$1\\\"\">>~/.bashrc\necho \"export V=\\\"$2\\\"\">>~/.bashrc\necho \"export K=\\\"$3\\\"\">>~/.bashrc\necho \"export E=\\\"$4\\\"\">>~/.bashrc\necho \"export B=\\\"$5\\\"\">>~/.bashrc\necho \"PS1=\\\"\\\$H:\\\h: \\\"\">>~/.bashrc\nchmod 755 ~/eth2/t[1-9] ~/eth2/e?"; }
function cc0 {
  if [[ ${1%%.*} -eq 192 ]];then local u=eu;else local u=ubuntu;fi;local s="$u@$1"
  scp -P 22 ~/eth2/s? ~/eth2/keth ~/i0 $s:~
  echo -e "\n\n\n\nsudo -i\nbash /home/$u/s0\n\n\n\n"
  ssh -p 22 $s
  cc1 $1 $2
  cc2 $1 $2
  zcp $2 $1: ~/i1
  zsh $2 $1 'sh i1'
  echo -e "\n\nky # gerar key & copiar para keth\nt2 # setup\n\n"
  zsh $2 $1
}
function nip { echo ${N%%:*}; }
function npt { echo ${N#*:}; }
function nfc {
  local d='/mnt/mp4'
  if ! systemctl is-active --quiet nfs-client.target;then
    sudo apt update                &>> nfc.out
    sudo apt install nfs-common -y &>> nfc.out
  fi
  [[ -d $d        ]] || sudo mkdir -p $d
  [[ -d $d/movie/ ]] || sudo mount 192.168.8.28:$1 $d
  ll $d
}
function nfj { nfc '/media/mp4'; }
function nfp { nfc '/var/lib/plexmediaserver/mp4'; }
function z7z {
  local a=${1:-1}
  local u=$(whoami)
  local f="/home/$u/cs$a.7z"
  local d="/media/$u/cs$a"
  [[ -d $d ]] || return
  sudo 7z a -p$W -mhe=on "$f" "$d"
  sudo chown "$u:$u" "$f"
}
function ufz { echo "$B"|gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 -c $1; }
function zfu { echo "$B"|gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 -d $1; }

alias v1='esl ${N%%:*} ${N#*:}'
alias v2='esl ns3238168.ip-57-129-52.eu 2020'

alias z1='esl hrv-zotac1'
alias zr='esl hrv-zotac1'
alias zl="zsh 2021 $(dnn hrv-zotac1) 'tail -n20 ~/rt-pfsense-wan-check.log'"
alias mr='echo meo:$V ;telnet 192.168.8.1'

alias z2="esl hrv-zotac2"
alias z3="esl hrv-zotac3"
alias z4="esl hrv-zotac4"
alias z5="esl hrv-intel5"
alias z6="esl hrv-intel6"

alias zp="ecv hrv-intel6 hrv-intel5 hrv-zotac4 hrv-zotac3 hrv-zotac2"
alias zo="ocv hrv-intel6 hrv-intel5 hrv-zotac4 hrv-zotac3 hrv-zotac2;rcp hrv-zotac1"
alias zk="ccp hrv-zotac2"
alias vp='ecp ${N%%:*} ${N#*:}'
alias vo='ocp ${N%%:*} ${N#*:}'
alias vk='ccp ${N%%:*} ${N#*:}'

alias pi="ping \$(nip)"
alias gp='cd ~/eth2;git pull;cd'
alias gc='cd ~/eth2;git commit -am "cleanup";git push;cd'
alias gd='cd ~/eth2;git diff'
alias gt='cd ~/eth2;git status'
alias gv='cd;vi eth2/t[1-8] eth2/e[1-9]'

alias ky='ssh-keygen -f ~/.ssh/id_ed25519 -t ed25519 -C "$(whoami)@$(hostname)";cat ~/.ssh/id_ed25519.pub'
alias lk="ei0 \$H \$E \$R \$V \$(npt) >~/i0;ei1 \$H \$V \$K \$E \$B >~/i1;cc0 \$(nip) \$(npt)"
alias fw='echo "export R=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c50)\"";echo "export H=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c30)\"";echo "export V=\"$(</dev/urandom tr -dc "A-Za-z0-9"|head -c8)\"";echo "export K=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c60)\"";echo "export W=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c60)\"";'
alias xx='exit'
alias rq='msh ip a;msh ip r;systemctl is-active --quiet systemd-networkd && msh networkctl status;msh resolvectl status;erq'
