#!/usr/bin/bash

source /home/eth/eth2/a2

function nrs { sudo netplan apply;sudo systemctl stop systemd-resolved;sleep 9;sudo systemctl start systemd-resolved;sleep 9;resolvectl status; }
function ecp { echo "scp $1:~/eth2";mcp -q ~/eth2/t[1-9] ~/eth2/e? ~/eth2/a? $1:~/eth2; }
function ocp { echo "scp $1:"      ;mcp -q ~/eth2/asrv $1:~/.bash_aliases;mcp -q ~/eth2/keth $1:~/.ssh/authorized_keys; }
function ccp { echo "scp $1:"      ;mcp -q ~/eth2/cns.keys.gpg ~/eth2/hernanirvaz-f2e8fb66dbc0.json.gpg $1:; }
function pcp { echo "scp $1:/root" ;mcp -q ~/eth2/keth $1:/root/.ssh/authorized_keys;mcp -q ~/eth2/rt-pfsense-wan-check.sh ~/eth2/rt-pfsense-log-check.sh $1:/root; }
function ecv { local s='';for s in "$@";do ecp $s;done; }
function ocv { local s='';for s in "$@";do ocp $s;done; }
function ei0 { echo -e "export H=\"$1\"\nexport E=\"$2\"\nexport R=\"$3\"\nexport V=\"$4\"\npr=$5"; }
function ei1 { echo -e "echo>>~/.bashrc\necho \"export PATH=\\\"\\\$PATH:/home/eth/eth2\\\"\">>~/.bashrc\necho \"export H=\\\"$1\\\"\">>~/.bashrc\necho \"export V=\\\"$2\\\"\">>~/.bashrc\necho \"export K=\\\"$3\\\"\">>~/.bashrc\necho \"export E=\\\"$4\\\"\">>~/.bashrc\necho \"export B=\\\"$5\\\"\">>~/.bashrc\necho \"PS1=\\\"\\\$H:\\\h: \\\"\">>~/.bashrc\nchmod 755 ~/eth2/t[1-9] ~/eth2/e?"; }
function cz0 {
  local u;if smt $1;then u=eu;else u=ubuntu;fi;local s="$u@$1"
  mcp -q 22 ~/eth2/s? ~/eth2/keth ~/i0 $s:~
  echo -e "\n\n\n\nsudo -i\nbash /home/$u/s0\n\n\n\n"
  msh $s 22
  mcp -q $2 ~/eth2/asrv                       $1:~/.bash_aliases
  mcp -q $2 ~/eth2/t[1-9] ~/eth2/e? ~/eth2/a? $1:~/eth2
  mcp -q $2 ~/i1                              $1:
  msh $1 $2 'sh i1'
  echo -e "\n\nky # gerar key & copiar para keth\nt2 # setup\n\n"
  msh $1 $2
}
function nfc {
  local d='/mnt/mp4'
  if ! systemctl is-active --quiet nfs-client.target;then
    sudo apt-get update                &>> nfc.out
    sudo apt-get install nfs-common -y &>> nfc.out
  fi
  [[ -d $d        ]] || sudo mkdir -p $d
  [[ -d $d/movie/ ]] || sudo mount 192.168.8.28:$1 $d
  ll $d
}
function nfj { nfc '/media/mp4'; }
function nfp { nfc '/var/lib/plexmediaserver/mp4'; }
function z7z {
  local a=${1:-1}
  local u=$(whoami)
  local f="/home/$u/cs$a.7z"
  local d="/media/$u/cs$a"
  [[ -d $d ]] || return
  sudo 7z a -p$W -mhe=on "$f" "$d"
  sudo chown "$u:$u" "$f"
}
function gcf {
  local u='/conf/config.xml'
  if [[ -s $1 ]];then 
    ufz "$1";mv "$1.gpg" ~/eth2/"$3"  ;echo Found $(basename "$1")
    if [[ -d $4 ]];then cp "$1" "$4$u";echo Found "$4$u";fi
    rm "$1"
  fi
} 
function gcr { 
  local f;local s
  s='Downloads/config-hrv-zotac1.home.arpa';f=$(find ~/$s*.xml 2>/dev/null|sort -t. -k3n|tail -n1);gcf "$f" "$s" rt-pfsense.xml.gpg /media/eth/PFSENSE
  s='Downloads/ArcherC6v220220613137n'     ;f=$(find ~/$s*.bin 2>/dev/null|tail -n1)              ;gcf "$f" "$s" rt-tplink.bin.gpg
  s='rt-pfsense'                           ;f=$(find ~/$s*.txt 2>/dev/null|tail -n1)              ;gcf "$f" "$s"
  s='rt-LEOX'                              ;f=$(find ~/$s*.txt 2>/dev/null|tail -n1)              ;gcf "$f" "$s"
  s='rt-MEO'                               ;f=$(find ~/$s*.txt 2>/dev/null|tail -n1)              ;gcf "$f" "$s"
  s='rt-protectli'                         ;f=$(find ~/$s*.txt 2>/dev/null|tail -n1)              ;gcf "$f" "$s"
}
function rfu {
  local s;cd $HOME
  s='rt-pfsense'  ;[[ -s $s.txt ]] || { zfu eth2/$s.txt.gpg > $s.txt;[[ -s $s.txt ]] && echo Restored $s.txt; }
  s='rt-LEOX'     ;[[ -s $s.txt ]] || { zfu eth2/$s.txt.gpg > $s.txt;[[ -s $s.txt ]] && echo Restored $s.txt; }
  s='rt-MEO'      ;[[ -s $s.txt ]] || { zfu eth2/$s.txt.gpg > $s.txt;[[ -s $s.txt ]] && echo Restored $s.txt; }
  s='rt-protectli';[[ -s $s.txt ]] || { zfu eth2/$s.txt.gpg > $s.txt;[[ -s $s.txt ]] && echo Restored $s.txt; }
}

function vls {
  [[ $# -eq 0 ]] && return;local s='';local c=1;local p=2020 
  for s in $@;do 
    alias v$c="msh $s"
    alias pv$c="ping $s"
    alias kv$c="ei0 \$H \$E \$R \$V $p >~/i0;ei1 \$H \$V \$K \$E \$B >~/i1;cz0 $s $p"
    ((c++))
  done
  alias vp="ecv $@"
  alias vo="ocv $@"
}
function zls {
  [[ $# -eq 0 ]] && return;local s='';local c=1;local p=2020
  for s in $@;do 
    p=$(spn $s);c=${s/*[^0-9]/}
    alias pz$c="ping $(sin $s)"
  done
}
function kz {
  if [[ $# -eq 0 ]];then
    echo -e "kz (port|ip) [ip|port]\n\nip=last octet; Defaults port=2020, ip_last_octet=111"
    return
  fi 
  local p=$(spn 192.168.8.$1);local s=$(sio $1)
  if [[ $s -eq 111 ]];then
    p=${2:-$p};if [[ $1 -le 255 ]];then s=$1;else p=$1;fi
  else 
    p=$1;s=${2:-111}
  fi
  s="192.168.8.$s";echo "Setup ubuntu server: $s:$p"
  ei0 $H $E $R $V $p >~/i0;ei1 $H $V $K $E $B >~/i1;cz0 $s $p
} 
hlp () {
  cat <<'EOF'
z7z [1|2]               archive media cs1|cs2 encripted with 7z
ufz file                encrypt file
zfu file                decrypt file
rfu                     decrypt router config files
gcr                     git commit recent router config files
kz  (port|ip) [ip|port] setup server at ip last octet or port
EOF
}


zls hrv-zotac1 hrv-zotac2 hrv-zotac3 hrv-zotac4 hrv-intel5 hrv-intel6
vls ns31198432.ip-51-89-64.eu

alias wgp='sudo wg-quick down wg0'
alias wga='sudo wg-quick up   wg0'
# alias wge='sudo systemctl enable  wg-quick@wg0'
# alias wgd='sudo systemctl disable wg-quick@wg0'
alias wgs='sudo wg show'

alias mr='echo 192.168.1.254:$V ;telnet 192.168.1.254'
alias zp="ecv hrv-intel6 hrv-intel5 hrv-zotac4 hrv-zotac3 hrv-zotac2"
alias zo="ocv hrv-intel6 hrv-intel5 hrv-zotac4 hrv-zotac3 hrv-zotac2;pcp hrv-zotac1"
alias zk="ccp hrv-zotac3"

alias gp='cd ~/eth2;git pull;cd'
alias gc='cd ~/eth2;git commit -am "cleanup";git push;cd'
alias gd='cd ~/eth2;git diff'
alias gt='cd ~/eth2;git status'

alias fw='echo "export R=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c50)\"";echo "export H=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c30)\"";echo "export V=\"$(</dev/urandom tr -dc "A-Za-z0-9"|head -c8)\"";echo "export K=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c60)\"";echo "export W=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c60)\"";'
