#!/usr/bin/bash

cunm=$(hostname)
cust=${cunm:0:3}

function sin {
  case ${1%%.*} in
  hrv-intel5) printf 192.168.8.37 ;;
  hrv-intel6) printf 192.168.8.40 ;;
  hrv-zotac1) printf 192.168.8.25 ;;
  hrv-zotac2) printf 192.168.8.28 ;;
  hrv-zotac3) printf 192.168.8.31 ;;
  hrv-zotac4) printf 192.168.8.34 ;;
  *) printf $1 ;;
  esac
}
function spn {
  local n
  case ${1%%.*} in
  hrv*) n=$((2020+${s##*[!0-9]})) ;;
  hrv-intel5) n=2025 ;;
  hrv-intel6) n=2026 ;;
  hrv-zotac1) n=2021 ;;
  hrv-zotac2) n=2022 ;;
  hrv-zotac3) n=2023 ;;
  hrv-zotac4) n=2024 ;;
  *) n=2020 ;;
  esac
  printf %i $n
}
function sht { [[ $(hostname -I|cut -d. -f1-3) = 192.168.8 ]]; } # source in my lAN network
function sot { nslookup $1 2>/dev/null 1>&2; } # DNS lookup exists
function sit { [[ $1 = 192.168.8.* ]]; } # destination to my lAN IPs
function snt { [[ $1 = hrv* ]]; } # destination to my lAN hostnames
function sdt { sit $1 || snt $1; } # destination to my lAN network
function srt { [[ $1 = 192.168.8.25 || $1 == hrv-zotac1* ]]; } # destination to my psSense router
function dnn { local s=$1;sot $s || s=$(sin $1);snt $1 && ! sht && s="$s.fruga.pt";srt $s && s="admin@$s";printf %s $s; }
function dnp { local s=$1;sot $s || s=$(sin $1);local n=${s##*[!0-9]};local p=2020;sdt $s && p=$((p+n));printf %i $p; }
function dnz { local p=$2;[[ $p ]] || p=$(dnp $1);printf %i $p; }
function zsh { ssh -p $1 -i ~/.ssh/id_ed25519 $2 "$3"; }

function msh { echo -e "\n\e[5;32m${*^^}\e[0m";eval "$*"; }
function icm { dig +domain=unknown.home.arpa AAAA $@;dig +domain=home.arpa AAAA $@;dig +domain=unknown.home.arpa A $@;dig +domain=home.arpa A $@; }
function dsh { msh resolvectl flush-caches;icm hrv-zotac1 hrv-zotac2 hrv-zotac3 hrv-zotac4 hrv-intel5 hrv-intel6 hrv-zen hrv-lenovo lgwebostv lgwebostv0 dreamevacuumr2364a pixel-9-pro-xl|grep -E '^[a-z]{3}'|sort; }
function esl { local p=$(dnz $1 $2);local s=$(dnn $1);echo -e "\nzsh $s:$p     ";zsh $p $s; }
function erq { local q=${1:-github.com};msh resolvectl query $q; }
function nrs { sudo netplan apply;sudo systemctl stop systemd-resolved;sleep 9;sudo systemctl start systemd-resolved;sleep 9;resolvectl status; }

function zcp { local p=$1;local d=$2;shift;shift;scp -P $p -i ~/.ssh/id_ed25519 $@ "$d"; }
function ecp { local p=$(dnz $1 $2);local s=$(dnn $1);echo -e "\nzcp $s:$p eth2";cc2 $1 $p; }
function ocp { local p=$(dnz $1 $2);local s=$(dnn $1);echo -e "\nzcp $s:$p ocp ";cc1 $1 $p;zcp $p $s:~/.ssh/authorized_keys ~/eth2/keth; }
function ccp { local p=$(dnz $1 $2);local s=$(dnn $1);echo -e "\nzcp $s:$p ccp ";zcp $p $s: ~/eth2/cns.keys.gpg;zcp $p $s: ~/eth2/hernanirvaz-f2e8fb66dbc0.json.gpg; }
function rcp { local p=$(dnz $1 $2);local s=$(dnn $1);echo -e "\nzcp $s:$p rcp ";zcp $p $s:~/.ssh/authorized_keys ~/eth2/keth;zcp $p $s: ~/eth2/rt-pfsense-wan-check.sh; }
function cc1 { zcp $2 $(dnn $1):~/.bash_aliases ~/eth2/asrv            ; }
function cc2 { zcp $2 $(dnn $1):~/eth2          ~/eth2/t[1-9] ~/eth2/e?; }
function ecv { local s='';for s in $@;do ecp $s;done; }
function ocv { local s='';for s in $@;do ocp $s;done; }
function ei0 { echo -e "export H=\"$1\"\nexport E=\"$2\"\nexport R=\"$3\"\nexport V=\"$4\"\npr=$5"; }
function ei1 { echo -e "echo>>~/.bashrc\necho \"export PATH=\\\"\\\$PATH:/home/eth/eth2\\\"\">>~/.bashrc\necho \"export H=\\\"$1\\\"\">>~/.bashrc\necho \"export V=\\\"$2\\\"\">>~/.bashrc\necho \"export K=\\\"$3\\\"\">>~/.bashrc\necho \"export E=\\\"$4\\\"\">>~/.bashrc\necho \"export B=\\\"$5\\\"\">>~/.bashrc\necho \"PS1=\\\"\\\$H:\\\h: \\\"\">>~/.bashrc\nchmod 755 ~/eth2/t[1-9] ~/eth2/e?"; }
function cc0 {
  if sdt $1;then local u=eu;else local u=ubuntu;fi;local s="$u@$1"
  scp -P 22 ~/eth2/s? ~/eth2/keth ~/i0 $s:~
  echo -e "\n\n\n\nsudo -i\nbash /home/$u/s0\n\n\n\n"
  ssh -p 22 $s
  cc1 $1 $2
  cc2 $1 $2
  zcp $2 $1: ~/i1
  zsh $2 $1 'sh i1'
  echo -e "\n\nky # gerar key & copiar para keth\nt2 # setup\n\n"
  zsh $2 $1
}
function nip { echo ${N%%:*}; }
function npt { echo ${N#*:}; }
function nfc {
  local d='/mnt/mp4'
  if ! systemctl is-active --quiet nfs-client.target;then
    sudo apt update                &>> nfc.out
    sudo apt install nfs-common -y &>> nfc.out
  fi
  [[ -d $d        ]] || sudo mkdir -p $d
  [[ -d $d/movie/ ]] || sudo mount 192.168.8.28:$1 $d
  ll $d
}
function nfj { nfc '/media/mp4'; }
function nfp { nfc '/var/lib/plexmediaserver/mp4'; }
function z7z {
  local a=${1:-1}
  local u=$(whoami)
  local f="/home/$u/cs$a.7z"
  local d="/media/$u/cs$a"
  [[ -d $d ]] || return
  sudo 7z a -p$W -mhe=on "$f" "$d"
  sudo chown "$u:$u" "$f"
}
function ufz { echo "$B"|gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 -c $1; }
function zfu { echo "$B"|gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 -d $1; }

alias v1='esl ${N%%:*} ${N#*:}'
alias v2='esl ns3238168.ip-57-129-52.eu 2020'

alias z1='esl hrv-zotac1'
alias zr='esl hrv-zotac1'
alias zl="zsh 2021 $(dnn hrv-zotac1) 'tail -n20 ~/rt-pfsense-wan-check.log'"
alias mr='echo meo:$V ;telnet 192.168.8.1'

alias z2="esl hrv-zotac2"
alias z3="esl hrv-zotac3"
alias z4="esl hrv-zotac4"
alias z5="esl hrv-intel5"
alias z6="esl hrv-intel6"

alias zp="ecv hrv-intel6 hrv-intel5 hrv-zotac4 hrv-zotac3 hrv-zotac2"
alias zo="ocv hrv-intel6 hrv-intel5 hrv-zotac4 hrv-zotac3 hrv-zotac2;rcp hrv-zotac1"
alias zk="ccp hrv-zotac2"
alias vp='ecp ${N%%:*} ${N#*:}'
alias vo='ocp ${N%%:*} ${N#*:}'
alias vk='ccp ${N%%:*} ${N#*:}'

alias pi="ping \$(nip)"
alias gp='cd ~/eth2;git pull;cd'
alias gc='cd ~/eth2;git commit -am "cleanup";git push;cd'
alias gd='cd ~/eth2;git diff'
alias gt='cd ~/eth2;git status'
alias gv='cd;vi eth2/t[1-8] eth2/e[1-9]'

alias ky='ssh-keygen -f ~/.ssh/id_ed25519 -t ed25519 -C "$(whoami)@$(hostname)";cat ~/.ssh/id_ed25519.pub'
alias lk="ei0 \$H \$E \$R \$V \$(npt) >~/i0;ei1 \$H \$V \$K \$E \$B >~/i1;cc0 \$(nip) \$(npt)"
alias fw='echo "export R=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c50)\"";echo "export H=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c30)\"";echo "export V=\"$(</dev/urandom tr -dc "A-Za-z0-9"|head -c8)\"";echo "export K=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c60)\"";echo "export W=\"$(</dev/urandom tr -dc "A-Za-z0-9?%&_+=@~#\,.?/"|head -c60)\"";'
alias xx='exit'
alias rq='msh ip a;msh ip r;systemctl is-active --quiet systemd-networkd && msh networkctl status;msh resolvectl status;erq;sht && dsh'
