#!/usr/bin/bash

source /home/eth/eth2/a2

if [[ $cunm = hrv-zotac2 ]];then
  mt1() { id jellyfin &>>/dev/null; }
  mt2() { id plex     &>>/dev/null; }
  mdi() { if mt2;then printf /var/lib/plexmediaserver/mp4;else printf $mdld;fi; }
  mus() { if mt2;then printf plex                        ;else printf eth  ;fi; }
  rsy() { ecn rsync --delete --numeric-ids $4 -avhe \"ssh -4p $3\" $1 $2; }
  rsl() { ecn rsync --delete --numeric-ids $3 -avh                 $1 $2; }
 
  smv() { rsy       $mdld/movie $(sin $1): $(spn $1) $2;sleep 9; }
  pmv() { rsy $(sin $1):~/movie $mdld      $(spn $1) $2;sleep 9; }
  stv() { rsy       $mdld/tv    $(sin $1): $(spn $1) $2;sleep 9;rsy       $mdld/tv2 $(sin $1): $(spn $1) $2; }
  ptv() { rsy $(sin $1):~/tv    $mdld      $(spn $1) $2;sleep 9;rsy $(sin $1):~/tv2 $mdld      $(spn $1) $2; }

  slt() { rsy       $mdld/lust  $(sin $1): $(spn $1) $2;sleep 9; }
  plt() { rsy $(sin $1):~/lust  $mdld      $(spn $1) $2;sleep 9; }
  sdk() { rsy       $dkcd       $(sin $1): $(spn $1) $2;sleep 9; }
  pdk() { rsy $(sin $1):~/$dkcn $dkcd      $(spn $1) $2;sleep 9; }
  # slt() { rsl       $mdld/lust  $mrpd                $2;sleep 9; }
  # plt() { rsl       $mrpd/lust  $mdld                $2;sleep 9; }
  # sdk() { rsl       $dkcd       $mrpd                $2;sleep 9; }
  # pdk() { rsl       $mrpd/$dkcn $dkcd                $2;sleep 9; }

  sal() { stv hrv-zotac3;smv hrv-zotac4;slt hrv-zotac4;sdk hrv-zotac3; } # --size-only option to avoid timestamp backups
  pal() { ptv hrv-zotac3;pmv hrv-zotac4;plt hrv-zotac4;pdk hrv-zotac3; }
  fi0() { echo findls $1 $mdld;find $mdld -name "*.$1" -print; }
  fi1() { echo findrm $1 $mdld;find $mdld -name "*.$1" -exec sudo rm {} \;; }
  fll() { if [[ $1 ]];then fi0 $1;else fi0 txt;fi0 jpg;fi; }
  frm() { if [[ $1 ]];then fi1 $1;else fi1 txt;fi1 jpg;fi; }
  fom() { echo "ch[own|mod] $meui:$megi $mdld";sudo chown $meui:$megi -R $mdld;sudo find $mdld -type d -exec chmod 755 {} \;;sudo find $mdld -type f -exec chmod 644 {} \;; }
  ftf() { find "$1" \( -path "$1/movie" -o -path "$1/tv" \) -prune -o \( -iname "*.mp4" -or -iname "*.mkv" -or -iname "*.avi" \) -printf  "$2\n"; }
  ftr() { find "$1" \( -path "$1/movie" -o -path "$1/tv" \) -prune -o \( -iname "*.mp4" -or -iname "*.mkv" -or -iname "*.avi" \) -exec e5 "$2" {} \;; }
  ft1() { local o=${1:-/mnt/data/downloads/complete};ftf "$o" %h|grep -Po '\.[0-9]{2}\.\K[a-zA-Z]+'           |sort -u; }
  ft2() { local o=${1:-/mnt/data/downloads/complete};ftf "$o" %f|grep -Po '\.[0-9]{2}\.\K[a-zA-Z]+\.[a-zA-Z]+'|sort -u; }
  ftv() {
    local o=${1:-/mnt/data/downloads/complete}
    local d=${2:-/media/mp4/lust/ftv}
    ftr "$o" "$d"
    ftf "$o" 'rm -rf "%h"'
  }
  hlp () {
    cat <<'EOF'
{ps}{mv|tv|lt|al}       pull|sync movie|tv|lt|all
f{ll|rm|om}             list|remove|permission files
r{ll|cd|pr|ar}          list|dir|para|arranca transmissions
m{cd|up|dw|rs|st|ud|lg} media dir|up|down|restart|status|update|logs
ft{12v} [o] [d]         ft[1|2] names [o]rigin|ftv mv [o]rigin [d]desino command 
{ufz|zfu} file          encrypt|decrypt file
EOF
  }
  alias rcd="cd $trmd;pwd;du -hs \$(ls)|sort -h"
  alias rpr="docker compose -f $dkcc stop  transmission;t6 rco"
  alias rar="docker compose -f $dkcc start transmission;t6 rop"
  alias rll='docker exec transmission transmission-remote -l'
  alias mcd="cd $mdld;pwd;du -hs \$(ls)|sort -h"
  alias mup="docker compose -f $dkcc up -d"
  alias mdw="docker compose -f $dkcc down"
  alias mrs="docker compose -f $dkcc restart"
  alias mst="docker compose -f $dkcc ps"
  alias mud="docker compose -f $dkcc pull && docker compose -f $dkcc up -d"
  alias mlg="docker compose -f $dkcc logs -f"
  alias ct='tail -n10 cns.log'
  alias ce='cns ceth;tail -n10 cns.log'
elif [[ $cunm = hrv-intel5 || $cunm = hrv-intel6 ]];then
  alias aa='t6 ah'
elif [[ $cunm = hrv-zotac3 || $cunm = hrv-zotac4 ]];then
  alias aa='t6 ch'
fi

sht || alias aa='t6 ah'
alias pp='t6 bps'
alias hh='t6 hs0'
alias tt='t6 hsh'
