#!/usr/bin/bash

source /home/eth/eth2/a2

if [[ $cunm = hrv-zotac2 ]];then
  mt1() { id jellyfin &>>/dev/null; }
  mt2() { id plex     &>>/dev/null; }
  mdi() { if mt2;then printf /var/lib/plexmediaserver/mp4;else printf /media/mp4;fi; }
  mus() { if mt2;then printf plex                        ;else printf eth       ;fi; }
  rsy() { echo -e "\n\nrsync $4 -4p $3 $1 $2\n\n";rsync --delete --numeric-ids $4 -avhP -e "ssh -4p $3" $1 $2; }
  rsl() { echo -e "\n\nrsync $3 local  $1 $2\n\n";rsync --delete --numeric-ids $3 -avhP                 $1 $2; }
 
  smv() { rsy $2/movie $(sin $1): $(spn $1) $3;sleep 10; }
  stv() { rsy $2/tv2   $(sin $1): $(spn $1) $3;sleep 10;rsl $2/tv /mnt/bkp $3; }
  # stv() { rsy $2/tv2   $(sin $1): $(spn $1) $3;sleep 10;rsy $2/tv $(sin $1): $(spn $1) $3; }
  slt() { rsy $2/lust  $(sin $1): $(spn $1) $3;sleep 10; }
  sal() { local o=$(mdi);smv hrv-zotac4 $o;stv hrv-zotac3 $o;slt hrv-zotac4 $o; } # --size-only option to avoid timestamp backups

  pmv() { rsy $(sin $1):~/movie $2 $(spn $1) $3;sleep 10; }
  ptv() { rsy $(sin $1):~/tv2   $2 $(spn $1) $3;sleep 10;rsl /mnt/bkp/tv $2 $3; }
  # ptv() { rsy $(sin $1):~/tv2   $2 $(spn $1) $3;sleep 10;rsy $(sin $1):~/tv $2 $(spn $1) $3; }
  plt() { rsy $(sin $1):~/lust  $2 $(spn $1) $3;sleep 10; }
  pal() { local o=$(mdi);pmv hrv-zotac4 $o;ptv hrv-zotac3 $o;plt hrv-zotac4 $o; }

  fi0() { local d=$(mdi);echo findls $1 $d;find $d -name "*.$1" -print; }
  fi1() { local d=$(mdi);echo findrm $1 $d;find $d -name "*.$1" -exec sudo rm {} \;; }
  fll() { if [[ $1 ]];then fi0 $1;else fi0 txt;fi0 jpg;fi; }
  frm() { if [[ $1 ]];then fi1 $1;else fi1 txt;fi1 jpg;fi; }
  fom() { local d=$(mdi);echo "ch[own|mod] $meui:$megi $d";sudo chown $meui:$megi -R $d;sudo find $d -type d -exec chmod 755 {} \;;sudo find $d -type f -exec chmod 644 {} \;; }
  ftf() { find "$1" \( -path "$1/movie" -o -path "$1/tv" \) -prune -o \( -iname "*.mp4" -or -iname "*.mkv" -or -iname "*.avi" \) -printf  "$2\n"; }
  ftr() { find "$1" \( -path "$1/movie" -o -path "$1/tv" \) -prune -o \( -iname "*.mp4" -or -iname "*.mkv" -or -iname "*.avi" \) -exec e5 "$2" {} \;; }
  ft1() { local o=${1:-/mnt/data/downloads/complete};ftf "$o" %h|grep -Po '\.[0-9]{2}\.\K[a-zA-Z]+'           |sort -u; }
  ft2() { local o=${1:-/mnt/data/downloads/complete};ftf "$o" %f|grep -Po '\.[0-9]{2}\.\K[a-zA-Z]+\.[a-zA-Z]+'|sort -u; }
  ftv() {
    local o=${1:-/mnt/data/downloads/complete}
    local d=${2:-/media/mp4/lust/ftv}
    ftr "$o" "$d"
    ftf "$o" 'rm -rf "%h"'
  }
  hlp () {
    cat <<'EOF'
{ps}{mv|tv|lt|al}       pull|sync movie|tv|lt|all
f{ll|rm|om}             list|remove|permission files
r{ll|cd|pr|ar}          list|dir|para|arranca transmissions
m{cd|up|dw|rs|st|ud|lg} media dir|up|down|restart|status|update|logs
ft{12v} [o] [d]         ft[1|2] names [o]rigin|ftv mv [o]rigin [d]desino command 
{ufz|zfu} file          encrypt|decrypt file
EOF
  }
  alias rcd="cd $trdi;pwd;du -hs \$(ls)|sort -h"
  alias rpr='cd ~/media-stack && docker compose stop  transmission;t6 rco'
  alias rar='cd ~/media-stack && docker compose start transmission;t6 rop'
  alias rll='docker exec transmission transmission-remote -l'
  alias mcd="cd $mddi;pwd;du -hs \$(ls)|sort -h"
  alias mup='cd ~/media-stack && docker compose up -d'
  alias mdw='cd ~/media-stack && docker compose down'
  alias mrs='cd ~/media-stack && docker compose restart'
  alias mst='cd ~/media-stack && docker compose ps'
  alias mud='cd ~/media-stack && docker compose pull && docker compose up -d'
  alias mlg='cd ~/media-stack && docker compose logs -f'
  alias ct='tail -n10 cns.log'
  alias ce='cns ceth;tail -n10 cns.log'
elif [[ $cunm = hrv-intel5 || $cunm = hrv-intel6 ]];then
  alias aa='t6 ah'
elif [[ $cunm = hrv-zotac3 || $cunm = hrv-zotac4 ]];then
  alias aa='t6 ch'
fi

sht || alias aa='t6 ah'
alias pp='t6 bps'
alias hh='t6 hs0'
alias tt='t6 hsh'
