#!/bin/bash

echo "--> Creating RAID-0 array (/dev/md0)..."
sudo mdadm --create --verbose /dev/md0 --level=0 --raid-devices=3 /dev/nvme0n1p2 /dev/nvme1n1p1 /dev/nvme2n1p1
sync
echo "--> Probing devices immediately after RAID creation..."
sudo partprobe # Attempt to force kernel update
sleep 15
sync
echo "--> Verification (mdstat after probe):"
cat /proc/mdstat
echo "--> Verification (lsblk after probe):"
lsblk /dev/md0

read -p "Press Enter ONLY IF OK"
echo "--> Partitioning the RAID array /dev/md0..."
sudo parted -s /dev/md0 mklabel gpt # Create GPT label on the RAID device
# Create one partition spanning the whole array, hint it's for ext4
sudo parted -s -a optimal /dev/md0 mkpart primary ext4 0% 100%
sync

echo "--> Informing kernel about partition on RAID array..."
sudo partprobe /dev/md0
sleep 5
sync
echo "--> Verification (lsblk):"
lsblk /dev/md0 # Should now show md0p1
