#!/bin/bash

# Ensure script is run with root privileges
if [ "$(id -u)" -ne 0 ]; then
  echo "This script requires root privileges. Please run with sudo."
  exit 1
fi

echo "--> Creating RAID-0 array (/dev/md0)..."
mdadm --create --verbose /dev/md0 --level=0 --raid-devices=3 /dev/nvme0n1p2 /dev/nvme1n1p1 /dev/nvme2n1p1
echo "--> Probing devices immediately after RAID creation..."
partprobe
sleep 15
sync

echo "--> Verification (mdstat after probe):"
cat /proc/mdstat
echo "--> Verification (lsblk after probe):"
lsblk /dev/md0

read -p "Press Enter ONLY IF OK"
echo "--> Partitioning the RAID array /dev/md0..."
parted -s /dev/md0 mklabel gpt                            # Create GPT label on the RAID device
parted -s -a optimal /dev/md0 mkpart primary ext4 0% 100% # Create one partition spanning the whole array, hint its for ext4
sync

echo "--> Informing kernel about partition on RAID array..."
partprobe /dev/md0
sleep 15
sync
echo "--> Verification (lsblk): Should now show md0p1"
lsblk /dev/md0
