#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
  echo "This script requires root privileges. Please run with sudo."
  exit 1
fi

echo "--> Formatting ESP (/dev/nvme0n1p1)..."
mkfs.fat -F 32 -n ESP /dev/nvme0n1p1
sync

echo "--> Formatting Root partition (/dev/md0p1)..."
mkfs.ext4 -L ROOT_RAID0 /dev/md0p1
sync
echo "--> Filesystem formatting complete."
