#!/bin/bash

source /home/eth/eth2/t1

swu 'INSTALAR GETH';sex "mkdir -p $p08/geth";sau eth1;sjw;cmw $p08 755 eth1;cmw $p08/geth 700 eth1
gtv $1 $2
maxp=10
pp2p=30303;ndp || pp2p=30304
othe="--http.corsdomain 'chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn' --http.vhosts '*'"                                                            # for metamask
othe="$othe --cache 16384"                                                                                                                                  # after v1.30.0 NOT recomended
othe="$othe --state.scheme=path"                                                                                                                            # after v1.14+ default
othe=''
apip='127.0.0.1'
if [[ $cunm = $inm5 ]];then apip="$iip5";else apip="$iip6";fi
cd
cat <<-EOF > $s10.service
[Unit]
Description=Geth Execution Client
Wants=network-online.target
After=network-online.target

[Service]
User=eth1
Group=eth1
Restart=on-failure
RestartSec=60
StartLimitIntervalSec=600
StartLimitBurst=9
TimeoutStopSec=600
ExecStart=$p00/geth --datadir $p08 --mainnet --port $pp2p --http --http.addr $apip --authrpc.addr $apip --maxpeers $maxp --authrpc.jwtsecret $p58/jwt$othe
ExecStopPost=+$p02/eth2/t7 GETHSTP \$SERVICE_RESULT \$EXIT_CODE \$EXIT_STATUS

[Install]
WantedBy=multi-user.target
EOF
sex "mv $s10.service $p04";cmw $p04/$s10.service 644
