#!/bin/bash

source /home/eth/eth2/t1

swu 'INSTALAR NETHERMIND';sex 'apt install libsnappy-dev libc6-dev libc6 unzip -y';sex "mkdir -p $p61";sau eth1;sjw;cmw $p61 755 eth1
nnv N $1 $2
maxp=10
pp2p=30303;ndp || pp2p=30304
# abrb=11052984
fptv=400  # Gb
if [[ $cunm = $inm5 ]];then apip="$iip5";elif [[ $cunm = $inm6 ]];then apip="$iip6";else apip='127.0.0.1';fi
othe=''
othe="$othe --network-maxactivepeers $maxp --network-discoveryport $pp2p --network-p2pport $pp2p"
othe="$othe --jsonrpc-enabled true --jsonrpc-host $apip --jsonrpc-enginehost $apip --jsonrpc-engineport 8551 --jsonrpc-jwtsecretfile $p58/jwt"
othe="$othe --sync-snapsync true"
# othe="$othe --sync-ancientbodiesbarrier $abrb --sync-ancientreceiptsbarrier $abrb"
othe="$othe --pruning-mode Hybrid --pruning-fullpruningtrigger VolumeFreeSpace --pruning-fullpruningthresholdmb $((fptv*1024))"
othe="$othe --Blocks.TargetBlockGasLimit $((n56*10**6))"
cd
cat <<-EOF > $s44.service
[Unit]
Description=Nethermind Execution Client
Wants=network-online.target
After=network-online.target

[Service]
User=eth1
Group=eth1
Restart=always
RestartSec=60
TimeoutStopSec=400
RuntimeMaxSec=infinity
WorkingDirectory=$p61
Environment="DOTNET_BUNDLE_EXTRACT_BASE_DIR=$p61"
ExecStart=$p00/nethermind/nethermind --config mainnet --data-dir $p61$othe
ExecStopPost=+$p02/eth2/t7 NETHSTP \$SERVICE_RESULT \$EXIT_CODE \$EXIT_STATUS

[Install]
WantedBy=multi-user.target
EOF
sex "mv $s44.service $p04";cmw $p04/$s44.service 644
