#!/bin/bash

source /home/eth/eth2/t1

function jva { local f=$(basename $1);cp $1 $f.sav;cp $1 $f.new;echo -e "$2" >> $f.new;sex "cp $f.new $1"; }                                                  # add lines to end file

swu 'INSTALAR BESU';sex 'apt install default-jdk libjemalloc-dev -y';jva $p36 "$s23";cmw $p36 644 root                                                        # besu execution client needs
sex "mkdir -p $p09/data";sau eth1;sjw;cmw $p09 755 eth1;cmw $p09/data 700 eth1                                                                                # create dir & user for ec
unv $1                                                                                                                                                        # download/install besu binaries
alow='192.168.8.25,192.168.8.31,192.168.8.34'                                                                                                                 # my servers
maxp=25    # default
pp2p=30303;ndp || pp2p=30304
apip='127.0.0.1'
if [[ $cunm = $inm5 ]];then apip="$iip5";else apip="$iip6";fi
epec="--miner-enabled=true --miner-coinbase=\"$s26\""                                                                                                         # coincashew guide had these NOT USING
epec="--pruning-enabled=true"                                                                                                                                 # pruning deprecated for bonsai tries
epec="--sync-mode=X_SNAP --data-storage-format=BONSAI"                                                                                                        # recommend snap sync/bonsai
epec="$epec --p2p-port=$pp2p --rpc-http-enabled=true --rpc-http-host=$apip"                                                                                   # enable  rpc:8545
epec="$epec --rpc-http-cors-origins=chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn"                                                                      # for metamask
epec="$epec --max-peers=$maxp"                                                                                                                                # set p2p connections
epec="$epec --engine-jwt-secret=$p58/jwt --host-allowlist=$alow --engine-host-allowlist=$alow"                                                                # MERGE
epec="$epec --Xplugin-rocksdb-high-spec-enabled"                                                                                                              # boost Besu performance
cd
cat <<-EOF > $s11.service
[Unit]
Description=Besu Execution Client
Wants=network-online.target
After=network-online.target

[Service]
User=eth1
Group=eth1
Restart=always
RestartSec=60
StartLimitIntervalSec=600
StartLimitBurst=9
TimeoutStopSec=600
RuntimeMaxSec=infinity
Environment="JAVA_OPTS=-Xmx8g"
ExecStart=$p00/besu/bin/besu --data-path=$p09/data $epec
ExecStopPost=+$p02/eth2/t7 BESUSTP \$SERVICE_RESULT \$EXIT_CODE \$EXIT_STATUS

[Install]
WantedBy=multi-user.target
EOF
sex "mv $s11.service $p04";cmw $p04/$s11.service 644
