#!/bin/bash

hlp() {
    echo "Usage: $0 [-d] [-p] [extension]"
    echo "  Converts video files to a compatible MP4 format."
    echo "  -d          Force delete of the output file if it already exists."
    echo "  -p          Print work."
    echo "  extension   File extension to convert (default: avi)."
    exit 1
}

fdl=false
fpt=false
while getopts ":dp" opt; do
  case ${opt} in
    d) fdl=true;;
    p) fpt=true;;
    \?)
      echo "Invalid Option: -$OPTARG" 1>&2
      hlp
      ;;
  esac
done
shift $((OPTIND -1))

find . -type f -iname "*.${1:-avi}" | while read -r ifl; do
    ofl="${ifl%.*}.mp4"
    [[ "$fdl" == "true" ]] && rm -f "$ofl"
    [[ "$fpt" == "true" ]] && echo "Converting: '$ifl' to '$ofl'"
    [[ -f "$ofl"        ]] && continue

    ffmpeg -nostdin -i "$ifl" -loglevel error -map 0:v:0 -c:v libx264 -preset medium -crf 23 -pix_fmt yuv420p -movflags +faststart "$ofl"
    if [[ $? -eq 0 && -s "$ofl" ]]; then
        echo "SUCCESS: '$ifl' has been converted to '$ofl'."
    else
        echo "ERROR: Conversion failed for '$ifl'.";rm -f "$ofl"
    fi
done