#!/usr/bin/bash

[[ -d "$1" && -s "$2" ]] || exit 0
b=$(basename "$2")
c=$(basename $(dirname "$2"))
d='ftv[a-z]+\.[a-z]+\.([a-z]+\.[a-z]+\.[a-z]+\.)'
i='ftv[a-z]+\.([0-9]+\.[0-9]+\.[0-9]+\.)'
w='([a-z]+\.)';z='([a-z]+\.[a-z]+\.)'
f='.*([a-z0-9]{3})'
n=''
[[ $n ]] || n=$(sed -En "s%^$i$z$w$w$w$w$w$w$f\$%\L\2\3\4\5\6\7\8\1\9%ip" <<< "$b")
[[ $n ]] || n=$(sed -En "s%^$i$z$w$w$w$w$w$f\$%\L\2\3\4\5\6\7\1\8%ip"     <<< "$b")
[[ $n ]] || n=$(sed -En "s%^$i$z$w$w$w$w$f\$%\L\2\3\4\5\6\1\7%ip"         <<< "$b")
[[ $n ]] || n=$(sed -En "s%^$i$z$w$w$w$f\$%\L\2\3\4\5\1\6%ip"             <<< "$b")
[[ $n ]] || n=$(sed -En "s%^$i$z$w$w$f\$%\L\2\3\4\1\5%ip"                 <<< "$b")
[[ $n ]] || n=$(sed -En "s%^$i$z$w$f\$%\L\2\3\1\4%ip"                     <<< "$b")
[[ $n ]] || n=$(sed -En "s%^$i$w$f\$%\L\2\1\3%ip"                         <<< "$b")
[[ $n ]] || n=$(sed -En "s%^$d.*\$%\L\1$b%ip"                             <<< "$c")
[[ $n ]] || n="$b"
if [[ -s "$1/$n" ]]; then
  echo "echo mv \"$2\" \"$1/$n\""
else
  echo "mv -f \"$2\" \"$1/$n\""
fi
