#!/bin/sh

LANG=C
LC_ALL=C

grep -E '[0-9.]+ *ms.+[0-9.]+ *Mbit/s.+[0-9.]+*Mbit/s' e9.log | \
awk '{ps+=$4;ds+=$7;us+=$10;cn++} END {print "avg ping: " ps/cn " ms";print "avg download: " ds/cn " Mbit/s";print "avg upload: " us/cn " Mbit/s"}'
