#!/bin/sh

LANG=C
LC_ALL=C

stc () { local s='Ping|Download|Upload';{ date +"%Y-%m-%d %H:%M:%S";speedtest --simple 2>/dev/null|grep -E "$s";}|xargs|sed -E "s% +($s):%\t\1:%g"; }

if [ $1 ];then
    stc
else
    mc=$(date +%M);mr=$(awk -v m=0 -v x=59 "BEGIN{srand();print int(m+rand()*(x-m+1))}")
    [ "$mc" -eq "$mr" ] && stc >> e9.log 2>&1
fi
