#!/bin/bash

ip=$(hostname -I);if [[ ${ip%%.*} -eq 192 ]];then iu=eu;else iu=ubuntu;fi
source /home/$iu/i0

sc='/etc/ssh/sshd_config'
ss='/lib/systemd/system/ssh.socket'
sm='/etc/ssmtp/ssmtp.conf'
un=eth
sh=ssh
uh="/home/$un"
s1="s%^ *#* *Port *22 *$%Port $pr%i"
s1="$s1;s%^ *#* *PermitRootLogin  *.*$%PermitRootLogin no%i"
s1="$s1;s%^ *#* *PasswordAuthentication  *.*$%PasswordAuthentication no%i"
s1="$s1;s%^ *#* *PermitEmptyPasswords  *.*$%PermitEmptyPasswords no%i"
s1="$s1;s%^ *#* *KbdInteractiveAuthentication  *.*$%KbdInteractiveAuthentication no%i"
s1="$s1;s%^ *#* *UsePAM  *.*$%UsePAM no%i"
s2="s%^ *#* *root *=.*$%root=hernanilr@gmail.com%i"
s2="$s2;s%^ *#* *mailhub *=.*$%mailhub=mail.smtp2go.com:587\nAuthUser=fruga.pt\nAuthPass=$E\nUseSTARTTLS=YES%i"
s2="$s2;s%^ *#* *rewriteDomain *=.*$%rewriteDomain=fruga.pt%i"
s2="$s2;s%^ *#* *FromLineOverride *=.*$%FromLineOverride=YES%i"
s3="s%^ *ListenStream *=(.*):[0-9]+$%ListenStream=\1:$pr%i"
