#!/bin/bash

ip=$(hostname -I);if [[ ${ip%%.*} -eq 192 ]];then iu=eu;else iu=ubuntu;echo -e "\nvip1='$(hostname -I|cut -d' ' -f1)';vnd1='$(hostname).$(hostname -d)'\nFIX ~/eth2/t1\n";fi
source /home/$iu/s0

function sse { local f=$(basename $1);cp $1 $f.sav;sed -E "$2" $f.sav > $1;cp $1 $f.new;chmod $3 $1;chown $4 $1; }
function ssp { echo "change passwd ${2:-root}:$1";echo -e "$1\n$1"|passwd $2; }

echo -e "\napt update"
apt update -y           &>> apt.out
apt full-upgrade -y     &>> apt.out
apt dist-upgrade -y     &>> apt.out
apt autoremove          &>> apt.out
apt autoclean           &>> apt.out
sse $sc "$s1" 644 root:root;if [[ ${ip%%.*} -ne 192 ]];then sse $ss "$s3" 644 root:root;echo -e "$V\n$V"|passwd $iu;fi;systemctl daemon-reload;systemctl reload $sh;systemctl restart $sh
apt install ssmtp jq -y &>> apt.out
sse $sm "$s2" 640 root:mail
passwd -l root
adduser --disabled-password --comment "" $un
ssp $H $un
usermod -aG sudo $un
mkdir -p $uh/.ssh $uh/${un}2
mv /home/$iu/${un}keys $uh/.ssh/authorized_keys
chown -R $un:$un $uh/.ssh $uh/${un}2
chmod 700 $uh/.ssh
chmod 600 $uh/.ssh/authorized_keys
ssp $R
