#!/bin/bash

i="\n\e[5m"
f="\e[25m\n"

meeu="$(whoami)"
ethg="eth-geth"
ethb="eth-beacon"
ethv="eth-validator"
ethp="prometheus"
ethn="prometheus-node-exporter"
ethf="grafana-server"

# lighthouse version
vers="stable"
vers="v1.0.3"

# tipo instalacao; "duas" => N(geth,beacon) A(validator), "" => N(geth,beacon,validator)
tipo="duas"

# home0 87.196.199.110
# home1 89.181.65.217
# home2 83.132.8.1
bnhm="83.132.8.1"
bnip="207.180.214.8"
vcip="164.68.107.45"

# data is going here
dtdi="/var/lib/lighthouse"
becn="$dtdi/beacon"
vldt="$dtdi/validators"
