#!/bin/bash

meeu=$(whoami)
cunm=$(uname -n)
cust=${cunm:0:3}
zip1='192.168.8.25'
zip2='192.168.8.28'
zip3='192.168.8.31'
zip4='192.168.8.34'
iip5='192.168.8.37'
iip6='192.168.8.40'
znm1='hrv-zotac1'
znm2='hrv-zotac2'
znm3='hrv-zotac3'
znm4='hrv-zotac4'
inm5='hrv-intel5'
inm6='hrv-intel6'
vip1='161.97.85.32'
vip2='161.97.85.32'
vip3='161.97.85.32'
vnm1='vmi1007895.contaboserver.net'
vnm2='vmi1007895.contaboserver.net'
vnm3='vmi1007895.contaboserver.net'
if [[ $cust = hrv ]];then ciec=$iip6;else ciec=$vip1;fi;[[ $cunm = $inm5 ]] && ciec=$iip5
if [[ $cust = hrv ]];then cicc=$iip6;else cicc=$vip1;fi;[[ $cunm = $inm5 ]] && cicc=$iip5
cuvc=$znm4
nxvc=$znm4
cun1=$inm6
cun2=$inm5
cumv=$znm3

p00='/usr/local/bin'
p01='/var/log/syslog'
p02='/home/eth'
p03='/dev/null'
p04='/etc/systemd/system'
p05='/var/lib/lighthouse'  ;[[ $cunm = $inm5 || $cunm = $inm6 ]] && p05='/cl/lighthouse'
p06=$p02
p07='/usr/bin'
p08='/var/lib/goethereum'  ;[[ $cunm = $inm5 || $cunm = $inm6 ]] && p08='/el/goethereum'
p09='/var/lib/javaethereum';[[ $cunm = $inm5 || $cunm = $inm6 ]] && p09='/el/javaethereum'
p10="$p02/geth.log"
p11="$p02/besu.log"
p12="$p02/beacon.log"
p13="$p02/bmedias.log"
p14="$p02/barqivo.log"
p16="$p05/beacon"
p17="$p05/validators"
p18="$p17/slashing_protection.sqlite"
p19="$p02/validator_keys"
p20="$(dirname $p04)/timesyncd.conf"
p21='/etc/default/motd-news'
p22='/etc/netplan/00-installer-config.yaml'
p23='/etc/apt/apt.conf.d/50unattended-upgrades'
p24='/etc/update-motd.d/00-header'
p25='/etc/update-motd.d/10-help-text'
p26='/etc/grub.d/30_os-prober'
p27='/etc/logrotate.d/rsyslog'
p28='/etc/update-motd.d/97-overlayroot'
p29='/etc/bind/named.conf.options'
p30='/etc/default/named'
p31='/etc/ntp.conf'
p32='/etc/nginx/conf.d/plexmediaserver.conf'
p33='/etc/transmission-daemon/settings.json'
p34='/etc/hosts'
p35='/etc/ssh/ssh_config.d/ztc.conf'
p36='/etc/environment'
p37='/etc/fstab'
p38='/etc/prometheus'
p39="$p02/sys.rs"
p40="$p02/geth.rs"
p41="$p02/besu.rs"
p42="$p02/bn.rs"
p43='/sys/devices/system/cpu/intel_pstate/no_turbo'
p44='/sys/bus/usb/devices/1-0:1.0/authorized'
p45='/var/run/reboot-required'
p46="$p02/vc.rs"
p47='/etc/apt/preferences.d'
p48='/etc/default/grub'
p49="$p02/validator.log"
p50="$p02/restart.print"
p51='/etc/apt/apt.conf.d/20auto-upgrades'
p52="$p02/mev.log"
p53="export H=$H;$p02/eth2/t6"
p54="$p02/eth2/t5"
p55="/etc/nut/ups.conf"
p56="/etc/nut/upsmon.conf"
p57="/etc/nut/upsd.conf"
p58='/var/lib/jwtethereum'

e00="s%^ *#* *NTP *=.*$%NTP=$zip1 $zip2 time.google.com time.cloudflare.com time.facebook.com%i";if [[ $cunm = $cuvc || $cunm = $cun1 || $cunm = $cun2 || $cunm = $cumv ]];then e00="${e00};s%^ *#* *PollIntervalMaxSec *=.*$%PollIntervalMaxSec=1200%i";fi
e01='s%^ *ENABLED=.*$%ENABLED=0%i'
e02='s%bind[^"]*"%bind -4"%'
e03='s%^ */*\(.*codename}-updates.*$\)%\1%i;s%^ */* *Unattended-Upgrade::Mail .*$%Unattended-Upgrade::Mail "hernanilr@gmail.com";%i;s%^ */* *Unattended-Upgrade::OnlyOnACPower.*$%Unattended-Upgrade::OnlyOnACPower "false";%i'
e04='s%^ *printf%# printf%i'
e05='s%.*name *= *(.*)$%\1%p;q'
e06='s%timeout *=.*$%timeout=1%i'
e07='/dnssec-validation/q'
e08="s%^ *pool  *\([^a-z]\)%# pool \1%;s%^ *pool  *ntp.ubuntu.com%pool pool.ntp.org%"
e08="${e08};s%^ *#.*restrict.*192.*%restrict 192.168.8.0 mask 255.255.255.0 notrap nomodify%"
e08="${e08};/^ *#.*Specify/a \\"
e08="${e08}pool 0.de.pool.ntp.org iburst"
e08="${e08}\npool 1.de.pool.ntp.org iburst"
e08="${e08}\npool 0.pt.pool.ntp.org iburst"
e08="${e08}\npool 0.europe.pool.ntp.org iburst"
e09='s%.*url="(.*)"%\1%p'
e10="s%--execution-endpoint  *\([^ ]*/\)[0-9\.]*:8551[^ ]*%--execution-endpoint \1$zip4:8551%"
e11="s%--execution-endpoint  *\([^ ]*/\)[0-9\.]*:8551[^ ]*%--execution-endpoint \1$zip1:8551%"
e12="s%.*--execution-endpoint  *[^ ]*/\([0-9\.]*\):8551.*%\1%p"
e13='s%^ *#*NTP=.*$%NTP=time.google.com time.cloudflare.com time.facebook.com%i'
e14='s%--subscribe-all-subnets --import-all-attestations %%'
e15='s%--validator-monitor-file%--subscribe-all-subnets --import-all-attestations --validator-monitor-file%'
e16='s%--beacon-nodes *\([^ ]*:5052\),\([^ ]*:5052\)[^ ]*%--beacon-nodes \2,\1%'
e17="s%hrv-zotac\([0-9]\).*%hrv-zotac\1 ztc\1%;/127.0.1.1/a \\"
[[ $cunm = $znm1 ]] && e17="$e17\n$zip2\thrv-zotac2 ztc2\n$zip3\thrv-zotac3 ztc3\n$zip4\thrv-zotac4 ztc4\n$iip5\thrv-intel5 int5\n$iip6\thrv-intel6 int6"
[[ $cunm = $znm2 ]] && e17="$e17\n$zip1\thrv-zotac1 ztc1\n$zip3\thrv-zotac3 ztc3\n$zip4\thrv-zotac4 ztc4\n$iip5\thrv-intel5 int5\n$iip6\thrv-intel6 int6"
[[ $cunm = $znm3 ]] && e17="$e17\n$zip1\thrv-zotac1 ztc1\n$zip2\thrv-zotac2 ztc2\n$zip4\thrv-zotac4 ztc4\n$iip5\thrv-intel5 int5\n$iip6\thrv-intel6 int6"
[[ $cunm = $znm4 ]] && e17="$e17\n$zip1\thrv-zotac1 ztc1\n$zip2\thrv-zotac2 ztc2\n$zip3\thrv-zotac3 ztc3\n$iip5\thrv-intel5 int5\n$iip6\thrv-intel6 int6"
[[ $cunm = $inm5 ]] && e17="$e17\n$zip1\thrv-zotac1 ztc1\n$zip2\thrv-zotac2 ztc2\n$zip3\thrv-zotac3 ztc3\n$zip4\thrv-zotac4 ztc4\n$iip6\thrv-intel6 int6"
[[ $cunm = $inm6 ]] && e17="$e17\n$zip1\thrv-zotac1 ztc1\n$zip2\thrv-zotac2 ztc2\n$zip3\thrv-zotac3 ztc3\n$zip4\thrv-zotac4 ztc4\n$iip5\thrv-intel5 int5"
e17="$e17\n207.180.214.8\tvpsl"
e17="$e17\n173.249.42.190\tvpsm"
e17="$e17\n164.68.107.45\tvpss"
e18='s%.*fee_recipient"."\([^"]*\)".*pubkey":"\([^"]*\)".*%pubkey: \2, fee: \1%p'
e19='s%(http://)?192.168.8.([0-9]+:[0-9]+)%\2%gp'
e20='s%.*\(Temperature\|Sensor\|Package\|Core\|Composite\|temp[0-9]\).*: *\([-+][0-9][0-9]*\.[0-9]*\).*%\2%p'
e21='s%.* \([0-9]*:[0-9]*\):[0-9]*.*%\1%'
e22='s%.*pubkey": "\([^"]*\)".*%0x\1%p'
e23='/^ *\/swap/s%^%#%'
e24="s%download-dir\": \"[^\"]*\"%download-dir\": \"/sata/downloads\"%"
e24="$e24;s%incomplete-dir\": \"[^\"]*\"%incomplete-dir\": \"/sata/downloads\"%"
e24="$e24;s%lpd-enabled\": .*%lpd-enabled\": true,%"
e24="$e24;s%rpc-whitelist\": \"[^\"]*\"%rpc-whitelist\": \"127.0.0.1,192.168.8.*\"%"
e24="$e24;s%rpc-username\": \"[^\"]*\"%rpc-username\": \"eu\"%"
e24="$e24;s%rpc-password\": \"[^\"]*\"%rpc-password\": \"\"%"
e24="$e24;s%umask\": [0-9]*%umask\": 2%"
e25='/ext4  *defaults  */s%defaults%defaults,noatime%'
e26='s%(Current DNS).*:%   \1:%ip'
e27='s%GRUB_CMDLINE_LINUX_DEFAULT *= *"\(..*\)"%GRUB_CMDLINE_LINUX_DEFAULT="\1 pcie_aspm=off"%;s%GRUB_CMDLINE_LINUX_DEFAULT *= *""%GRUB_CMDLINE_LINUX_DEFAULT="pcie_aspm=off"%'
e28="s%APT::Periodic::Update-Package-Lists.*$%APT::Periodic::Update-Package-Lists \"1\";%i"
e28="${e28};s%APT::Periodic::Unattended-Upgrade.*$%APT::Periodic::Unattended-Upgrade \""
if [[ $cunm = $cuvc ]];then e28="${e28}5";elif [[ $cunm = $cun1 ]];then e28="${e28}2";elif [[ $cunm = $cun2 ]];then e28="${e28}1";else e28="${e28}1";fi
e28="${e28}\";%i;/APT::Periodic::Unattended-Upgrade/a \\"
e28="${e28}APT::Periodic::AutocleanInterval \"1\";"
e29="s%192\.168\.8\.%%g"
e29="$e29;s% *0x[a-z0-9]*…[a-z0-9]*%%g;s% *… *% %g"
e29="$e29;s% *[a-zA-Z0-9]*\.\.[a-zA-Z0-9]*%%g"
e29="$e29;s% *0x[a-z0-9]{64}%%g"  # 0x0383d08d331137c855430189831b7f0d58cbfd08152c43ec3a28e599691c1771
e29="$e29;s% *0x[a-z0-9]{40}%%g"  # 0x3f1962dd3666f186504d6e4c99f76e8e76ffc231
e29="$e29;s% *[a-z0-9]{64}%%g"    # daecf1068be9a5c179f28d24283fb17757ff5b49fcbca661d91358242a173519
e29="$e29;s% *[a-zA-Z0-9]{53}%%g" # 16Uiu2HAmVGPoShPq9FUCntTH5A36Z4FJtw1k3fAVNAGLTJZ7hRxH
e29="$e29;s%epoch:%ep:%gi"
e29="$e29;s%slot:%sl:%gi"
e29="$e29;s%block:%bl:%gi"
e29="$e29;s%block_root:%br:%gi"
e29="$e29;s%beacon_chain:%bc:%gi"
e29="$e29;s%canonical_head:%ch:%gi"
e29="$e29;s%service:%se:%gi"
e29="$e29;s%state:%ste:%gi"
e29="$e29;s%status:%stu:%gi"
e29="$e29;s%timestamp:%ts:%gi"
e29="$e29;s%set_as_head_delay:%shd:%gi"
e29="$e29;s%imported_delay:%ID:%gi"
e29="$e29;s%observed_delay:%OD:%gi"
e29="$e29;s%block_delay:%BD:%gi"
e29="$e29;s%proposer_index:%pi:%gi"
e29="$e29;s%snapdiffs=%sdf=%gi"
e29="$e29;s%triediffs=%tdf=%gi"
e29="$e29;s%triedirty=%tdt=%gi"
e29="$e29;s%^.*$cunm *%%"
e29="$e29;s%lighthouse%lh%"
e29="$e29;s%geth%eg%"
e29="$e29;s%besu%eu%"
e29="$e29;s% *finalized_root.*verified.,%%"
e29="$e29;s%\{[^}{]*\}%%g;s%\{[^}{]*\}%%g;s%\{[^}{]*\}%%g;s%ServerMessage\(ErrorMessage *\),? *%%gi;s%Reqwest\(reqwest::Error *\),? *%%gi;s% *=> *RequestFailed\(\)%%gi"
e30="$e29;s%(\.[0-9][0-9][0-9]) *.*peers:%\1 peers:%i"
e31="$e29;s%mev-boost%mv%"
e31="$e31;s%<html>.*</html>%%"
e31="$e31;s% +/ +(\\\[rn])*%%"
e31="$e31;s%ua *= *[^ ]* *%%"
e31="$e31;s%https?://([a-z\.-]+)(/[a-z0-9]+)*%\1%g"
e31="$e31;s%//[a-z0-9]+%%g"
e31="$e31;s%registerValidator%rV%g"
e31="$e31;s%numRegistrations%nR%g"
e31="$e31;s%slot *= *%sl=%"
e31="$e31;s%blockHash *= *%%"
e31="$e31;s%parentHash *= *%%"
e31="$e31;s%txRoot *= *%%"
e31="$e31;s%level *= *%%"
e31="$e31;s%method *= *%%"
e31="$e31;s%slotUID *= *[a-z0-9-]+ *%%"
e31="$e31;s%pubkey *= *[a-z0-9]+ *%%"
e31="$e31;s%path *= *[^ ]+ +%%"
e31="$e31;s%msg *= *%\tmsg=%"
e31="$e31;s%time *= *\"([^\"]+)\"%\1%"
e31="$e31;s%Get *..[^\" ]+..: *%GET %"
e31="$e31;s%Post *..[^\" ]+..: *%POST %"
e31="$e31;s%context deadline exceeded *%deadline %"
e31="$e31;s%\(Client.Timeout exceeded while awaiting headers\) *%(Timeout headers)%"
e32="$e29;s%,* *module: *[a-z_:0-9]*%%"
e33="s%^ *$p01%# $p01%"
e34='s%.*synchronized: *\([a-z]*\) *%\1%p'
e35='s%[0-9]*:[0-9]*:[0-9]*%%;s%[0-9]* users*,%%;s% average\([^,]*\).*%\1%;s%  *% %g'
e36='s%.*hrv-\(zotac\|intel\)[0-9] *\(.*\)%\2%;s%  *% %g'
e37='s%.*[0-9]*:[0-9]*:[0-9]*\.[0-9][0-9][0-9]?]?[Z ] *(.*)%\1%;s%\t\t*% %g;s%  *% %g'
e38='s% *((Server|Offset|Delay|Jitter)[^)(]*)\(?.*\)?%\1%ip'
e39='s%[^: ]*: *%%g;s%inactive%off%;s%active%on%'
e40='s%BEAC [0-9]*%BEAC 0%'
e41='s%.*Active: *(.*)%\1%p'
e42='s% *since.*;%%'
e43='s%peers\([ =]*\)[0-9]*%peers\1'
e44='s%.*highestBlock: *([0-9]+).*%\1%ip'
e45='s%.*currentBlock: *([0-9]+).*%\1%ip'
e46='s%.*highestBlock" *: *"0x([^"]+)".*%\1%ip'
e47='s%.*currentBlock" *: *"0x([^"]+)".*%\1%ip'
e48='s%.*result" *: *"0x([^"]+)".*%\1%ip'

g00="\n$p01\n{\n\trotate 7\n\tdaily\n\tmissingok\n\tnotifempty\n\tnocompress\n\tsharedscripts\n\tpostrotate\n\t\t/usr/lib/rsyslog/rsyslog-rotate\n\tendscript\n}"
g01='printf "Welcome to %s %s\\n" "$(uname -n)" "$DISTRIB_DESCRIPTION"'
g02=""
g02="$g02\n\tlisten-on { any; };"
g02="$g02\n\tlisten-on-v6 { none; };"
g02="$g02\n\tversion \"not currently available\";"
g02="$g02\n\trecursion yes;"
g02="$g02\n\tallow-recursion { localhost; 192.168.8.0/24; };"
g02="$g02\n\tallow-query { localhost; 192.168.8.0/24; };"
if [[ $cunm = $znm1 || $cunm = $znm2 ]];then
  if [[ $cunm = $znm1 ]];then
    g02="$g02\n\tallow-transfer { $zip2; };"
    g02="$g02\n\talso-notify { $zip2; };"
    g02="$g02\n\tmax-cache-size 70%;"
  else
    g02="$g02\n\tallow-transfer { $zip1; };"
    g02="$g02\n\talso-notify { $zip1; };"
    g02="$g02\n\tmax-cache-size 50%;"
  fi
else
  g02="$g02\n\tallow-transfer { none; };"
  g02="$g02\n\tmax-cache-size 10%;"
fi
g02="$g02\n\tquerylog yes;"
g02="$g02\n};"
g03=""
g03="$g03\nnetwork:"
g03="$g03\n  version: 2"
g03="$g03\n  renderer: networkd"
g03="$g03\n  ethernets:"
for m in $(ip l|sed -n 's%.* \([a-z0-9]*\): .* state UP .*%\1%p'|tail -n1);do
  g03="$g03\n    $m:"
  g03="$g03\n      dhcp4: false"
  [[ $cunm = $znm1 ]] && g03="$g03\n      addresses: [$zip1/24]"
  [[ $cunm = $znm2 ]] && g03="$g03\n      addresses: [$zip2/24]"
  [[ $cunm = $znm3 ]] && g03="$g03\n      addresses: [$zip3/24]"
  [[ $cunm = $znm4 ]] && g03="$g03\n      addresses: [$zip4/24]"
  [[ $cunm = $inm5 ]] && g03="$g03\n      addresses: [$iip5/24]"
  [[ $cunm = $inm6 ]] && g03="$g03\n      addresses: [$iip6/24]"
  g03="$g03\n      critical: true"
  g03="$g03\n      routes:"
  g03="$g03\n        - to: 0.0.0.0/0"
  g03="$g03\n          via: 192.168.8.254"
  g03="$g03\n          metric: 100"
  g03="$g03\n          on-link: true"
  g03="$g03\n      nameservers:"
  g03="$g03\n        addresses: [$zip1, $zip2]"
  g03="$g03\n      link-local: [ ]"
done
for m in $(ip l|sed -n 's%.* \([a-z0-9]*\): .* state DOWN .*%\1%p');do
  g03="$g03\n    $m:"
  g03="$g03\n      dhcp4: true"
  g03="$g03\n      activation-mode: off"
done
g04="upstream plex_backend { server $zip2:32400; keepalive 32; }"
g04="$g04\nserver {"
g04="$g04\nlisten 80;"
g04="$g04\nserver_name $zip2;"
g04="$g04\nsend_timeout 100m;"
g04="$g04\nresolver $zip2 $zip1 valid=300s;"
g04="$g04\nresolver_timeout 10s;"
g04="$g04\ngzip on;"
g04="$g04\ngzip_vary on;"
g04="$g04\ngzip_min_length 1000;"
g04="$g04\ngzip_proxied any;"
g04="$g04\ngzip_types text/plain text/css text/xml application/xml text/javascript application/x-javascript image/svg+xml;"
g04="$g04\ngzip_disable \"MSIE [1-6]\.\";"
g04="$g04\nclient_max_body_size 100M;"
g04="$g04\nproxy_set_header Host \$host;"
g04="$g04\nproxy_set_header X-Real-IP \$remote_addr;"
g04="$g04\nproxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
g04="$g04\nproxy_set_header X-Forwarded-Proto \$scheme;"
g04="$g04\nproxy_set_header Sec-WebSocket-Extensions \$http_sec_websocket_extensions;"
g04="$g04\nproxy_set_header Sec-WebSocket-Key \$http_sec_websocket_key;"
g04="$g04\nproxy_set_header Sec-WebSocket-Version \$http_sec_websocket_version;"
g04="$g04\nproxy_http_version 1.1;"
g04="$g04\nproxy_set_header Upgrade \$http_upgrade;"
g04="$g04\nproxy_set_header Connection \"Upgrade\";"
g04="$g04\nproxy_redirect off;"
g04="$g04\nproxy_buffering off;"
g04="$g04\nlocation / { proxy_pass http://plex_backend; }"
g04="$g04\n}"
g05=""
[[ $cunm = $znm1 ]] && g05="$g05\nHost ztc2\n  Port 2022\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc3\n  Port 2023\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc4\n  Port 2024\n  IdentityFile ~/.ssh/id_ed25519\n\nHost int5\n  Port 2025\n  IdentityFile ~/.ssh/id_ed25519\n\nHost int6\n  Port 2026\n  IdentityFile ~/.ssh/id_ed25519"
[[ $cunm = $znm2 ]] && g05="$g05\nHost ztc1\n  Port 2021\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc3\n  Port 2023\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc4\n  Port 2024\n  IdentityFile ~/.ssh/id_ed25519\n\nHost int5\n  Port 2025\n  IdentityFile ~/.ssh/id_ed25519\n\nHost int6\n  Port 2026\n  IdentityFile ~/.ssh/id_ed25519"
[[ $cunm = $znm3 ]] && g05="$g05\nHost ztc1\n  Port 2021\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc2\n  Port 2022\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc4\n  Port 2024\n  IdentityFile ~/.ssh/id_ed25519\n\nHost int5\n  Port 2025\n  IdentityFile ~/.ssh/id_ed25519\n\nHost int6\n  Port 2026\n  IdentityFile ~/.ssh/id_ed25519"
[[ $cunm = $znm4 ]] && g05="$g05\nHost ztc1\n  Port 2021\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc2\n  Port 2022\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc3\n  Port 2023\n  IdentityFile ~/.ssh/id_ed25519\n\nHost int5\n  Port 2025\n  IdentityFile ~/.ssh/id_ed25519\n\nHost int6\n  Port 2026\n  IdentityFile ~/.ssh/id_ed25519"
[[ $cunm = $inm5 ]] && g05="$g05\nHost ztc1\n  Port 2021\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc2\n  Port 2022\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc3\n  Port 2023\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc4\n  Port 2024\n  IdentityFile ~/.ssh/id_ed25519\n\nHost int6\n  Port 2026\n  IdentityFile ~/.ssh/id_ed25519"
[[ $cunm = $inm6 ]] && g05="$g05\nHost ztc1\n  Port 2021\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc2\n  Port 2022\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc3\n  Port 2023\n  IdentityFile ~/.ssh/id_ed25519\n\nHost ztc4\n  Port 2024\n  IdentityFile ~/.ssh/id_ed25519\n\nHost int5\n  Port 2025\n  IdentityFile ~/.ssh/id_ed25519"
g06='geth\['
g07='besu\[.*|'
g08='lighthouse\['
g09='mev-boost\['
g10="\($g06\|$g07\|$g08\|$g09\)"
g11="\($g06\|$g07\)"
g12="\($g06\|$g07\|$g08\)"
g13="$g11.*Imported"
g14='score:'
g15="DEBG.Peer.*$g14.\-\([0-9]\|[0-9][0-9]\|100\)\."
g16='DEBG.Measured.BN.latency'
g17='DEBG.Computed.attestation.selection.proofs'
g18='DEBG.Delayed.head.block'
g19='DEBG.Processed.HTTP.API.request'
g20='DEBG.Cloned.snapshot.for.late.block.skipped.slot'
g21='Block.from.API'
g22='Previous.epoch.attestation.s'
g23="\($g21\|$g22\)"
g24="$g06.*Chain.head.was.updated"
g25="[ =]INFO "
g26="$g25\| DEBG "
g27=' autostart.app-snap\| number.of.Error.Log.entries.increased'
g28='success'
g29='error'
g30='reorg_distance:'
g31='latency:'
g32='time_taken_ms:'
g33='duration='
g34='^[a-z][a-z][a-z]  *[0-9][0-9]*  *'
g35='^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
g36='^[0-9]{2}:[0-9]{2}$'
g37='^[0-9]+$'
g38='^[a-z]+$'

s00='systemctl'
s01="$s00 status"
s02="$s00 stop"
s03="$s00 start"
s04="$s00 enable"
s05="$s00 disable"
s06="$s00 restart"
s07='timedatectl'
s08='networkctl'
s09='resolvectl'
s10='eth-geth'
s11='eth-besu'
s12='eth-beacon'
s13='eth-validator'
s14='eth-mev-boost'
s15='transmission-daemon'
s16='prometheus'
s17='prometheus-node-exporter'
s18='grafana-server'
s19='systemd-timesyncd'
s20='named'
s21='plexmediaserver'
s22='nginx'
s23="JAVA_HOME='/usr/lib/jvm/java-11-openjdk-amd64'"
s24=""
s24="$s24\n1 [$cuvc]\tt6 tvc (vp,vd,scp slash $nxvc:~)"
s24="$s24\n2 [$nxvc]\tset $(basename $p19);t3 (keys,slash,srv)"
s24="$s24\n3\t\tcheck slash,srv,dirs"
s24="$s24\n4\t\trm vc_lock;cuvc=$nxvc"
s24="$s24\n5\t\tsleep 7m"
s24="$s24\n6\t\tt6 vea\n"
s25='0x27C7f54e48956A906aF2CBFBC8684b437776403d'
s26='0x534029B6371dc4453DD750Bc1198181F55C859fe'
s27="--connection=http://$zip4:5052 --allow-insecure-connections"
s28='Content-Type: application/json'
s29='offline-preparation'
s30='change-operations'
s31='timesync'
s32="http://$cicc:5052/eth/v1/validator/duties"
s33='https://boost-relay.flashbots.net/relay/v1/data/validator_registration?pubkey'
s34='.data[].slot'
s35='.data[].validator_index'
s36='Package: snapd'
s36="$s36\nPin: release a=*"
s36="$s36\nPin-Priority: -10"
s37='snap remove --purge'

n00=84
n01=84
n02=72
n03=48
n04=3
n05=120
n06=12
n07=99
n08=22238623
n09=1606824023
n10=4500
n11=500
n12=24
n13=42
n14=7128
n15=100000
n16=20
n17=80
n18=10
n19=70
n20=3000
n21=2
n22=200
n23=20000
n24=999
n25=70000
n26=200000
n27=19000
n28=10000
n29=18800
n30=4000;[[ $n30 -eq 0 ]] && n30=$(curl -sX GET 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=ETH&convert=EUR&CMC_PRO_API_KEY=3ae5f3df-bd71-489d-a9dd-b626995fba31'|sed 's%.*price.:\([0-9]*\.[0-9]*\).*%\1%')
n31=$($s01 $s12 2>$p03|sed -n 's%.*PID: *\([0-9]*\).*%\1%p')
n32=4
n33=30

j0='.ata_sct_temperature_history.table|join(" ")'
j1='.temperature.current'
j3='.nvme_smart_health_information_log.temperature_sensors|join(" ")'

w0='{if(match($0,/'
w1='([0-9]+(\.[0-9]+)?)(µs|ms|s)/,m)){if(m[3]=="s"){m[1]*=1000000};if(m[3]=="ms"){m[1]*=1000};printf("%.0f\n",m[1])}}'
w2='([0-9]+(\.[0-9]+)?)(µs|ms|s)/,m)){if(m[3]=="s"){m[1]*=1000};if(m[3]=="µs"){m[1]/=1000};printf("%.3f\n",m[1])}}'
w3='elapsed= *'
w4='elapsed: *'
w5=' in '
w6='imported_delay: +Some\('
w7='observed_delay: +Some\('
w8='block_delay:.+Some\('

unset b
b[ 11766]='0x93bf23a587f11f9eca329a12ef51296b8a9848af8c0fe61201524b14cb85b0c6fbd3e427501cdfa3b28719bd1ed96fff'
b[ 11767]='0xb5b0fc3d2ba577f3e2c7324f7ea4306f17eeee0f12c722f4fa83e45bf6c15477d50261bb2666c30f21ab71a26aeeeafb'
b[ 11770]='0x89e65476ab56bd1e102569531453620ef805adc4dea9caaa671a9b78a9e7ab61e713d038599364c9321ccc7b50f6bafd'
b[ 11771]='0xad37967c868bcbb69d73dcc82717bf5df57048703277ee48aaf64e753c71631bc17c46934da40fb5f8344390f9880c1a'
b[ 11772]='0xaf5e6791b3cbd587268b8da1822f9b0398cbd796eb4e9af856f561217981d9f9469d7f06accd9ae9ebe1b87d338330b4'
b[ 11773]='0x8606838b0ba9fcdcc2a61925305210cd3e44fe673d99bbb6f180242afa965f513bf7b8c298806171a05a12b6b3d5dd24'
b[ 11774]='0x880c275f193c45276bd250f25092305e06f12d725ecf9761b29051c1fd9a43c8c15c31012316ebad8459c4268824cb34'
b[ 11775]='0x8d7dcdd66f978549965d6ee6828adeaaf6ebb98e8dcb505d003e5369bc3513f090027e77faa0ae0246b6f08344872a73'
b[ 11776]='0x867cf5fd6d05017ef9df4d6ff157e2a8e97bbeb1522de427e82092e485fe7f305b651767997b2a21b6c91d83218493a1'
b[ 11777]='0xa2873632721623389d9bc5f455cb21e92244044cebd3bff6d5a809f78edde3de22c67ffc97a672c7ab573f7787c2c8bd'
b[ 11778]='0x8235d97c3530b6261eec3c658dd158ae5ed98481ead16a33837a083924028393634a71515affa76dcd371b943ee733ab'
b[ 11779]='0x88c2befbce7594c943a386573f03b8ce461457bf59267ffce3e6008b115d70259583ad5fe8d8b15487d84734a6ba8d17'
b[ 11780]='0x814fa0dbba56e8823bd00935e5c67b09c468d5734e80e6574c5984e736300431761bf083ef247f75a73eb1b4c01bde9b'
b[ 11782]='0xae1212d040fabbbd3e6947ecf4799ee5176a1d42e2848d8ebee030690aa4144143c30d32c52fb3931927355470c8f416'
b[ 11783]='0xad71900411ae03e4c63f23d7823ac3754e2ec0b8855693e15632536de677aca9f45ffeaf080ce234cbf3967723f79d45'
b[ 11784]='0xa96278aff172bdebb92e6312eb3b46b0b6ec58e5a9cad46f7958b8d795a97edfb425bc4f2cc5cf92b5a3355577ad6af5'
b[ 11786]='0xb2063ebff899e91b70de66115a2a0e590b8695930126f9d7cad090ca7f19d47b262c7c21dd9208ff6d4c8eea307b4ad3'
b[ 11788]='0x87615568c977431c53171ba39b1f559515e6273b5efe8b649eab88ba6a5abc7e2280bea2f61898b53079a1f1bd3f5caa'
b[449113]='0x968b8658458dfd6db14e10a7c0623573113e70c890d53db598f622f5a57300f1c1bd8cd1d27a7a5d882841f179928416'
b[449114]='0xa137c606f3f700789f2ef09bf71962b8023bee33d1b1db367a6dbb9bb3ad3d03c32247b2fec84afb57029b5de8169e7b'
b[449115]='0xb9c82583ba13992858faab8f813f9d1b4e50cbe5f2319b00fff781ff9e6cf5ff3e746f146f191d095cc72553597ecd2d'
b[449116]='0xae08e5f26f503c36ac554c5fbca45495405866ebfaa8976c3791e8461dee8ec34ce3e99e65c76db2bf7408a60d717299'
b[590905]='0xa8b644d7ea657f9abef0256155a08aac46f16a7ea083e53916c004702ffc8e93aed2d28114fe924653a0c2e570d82cf8'
b[590906]='0xa15449ffda354fc6f9de4bd6f020b419bf23e4256d6396213e81c302f7814a259931bd8f4c8e1e285a0f5222c5a1fa80'
b[590907]='0x82b93acde57a8c5ef6da79e79a8aca4438e035ec890f1bd7db7c356de4926841ab649e3d25c67e7714c976bc49e5a034'
b[1027307]='0x83c7c2d579df3b6f00513730e1bd2acb8c1515ecd0d158535d9e6c37dadbfbff20d9abd442527fdce970c3dd2818e710'

function i1t { [[ $cunm = $inm5 ]]; }                                                                                                                         # 1 nuc intel  test
function tsa { $s00 is-active  --quiet $1 2>$p03; }
function tse { $s00 is-enabled --quiet $1 2>$p03; }
function trs { if tsa $s19;then nex "$s06 $s19";else nex "$s06 ntp";fi; }
function swb { echo -e "\n\e[5m${1^^}\e[25m\n"; }
function swu { echo -e "${1^^}"; }
function swn { echo -e "$1"; }
function swl { echo -e "\n$1\n"; }
function sau { id $1 &>$p03 || sex "useradd --no-create-home --shell /bin/false $1"; }
function cmw { [[ $2 ]] && sex "chmod $2 $1";[[ $3 ]] && sex "chown $3:${4:-$3} $1"; }
function cex { swb "$1";echo $H|sudo -S $1       2>$p03; }
function nex { swn "$1";echo $H|sudo -S $1       2>$p03; }
function yex { swb "$1";echo $H|sudo -S $1 <<< y &>$p03; }
function pex {          echo $H|sudo -S $1       2>$p03; }
function sex {          echo $H|sudo -S $1       &>$p03; }
function dex { swl "$1";$1; }
function idi { local e="deny from $1 to $2"                       ;if [[ $4 ]];then nex "ufw $4 $e";else nex "ufw $e comment $3";fi; }
function ide { local e="deny from $1 port ${2/\// proto }"        ;if [[ $4 ]];then nex "ufw $4 $e";else nex "ufw $e comment $3";fi; }
function pde { local e="deny $1"                                  ;if [[ $3 ]];then nex "ufw $3 $e";else nex "ufw $e comment $2";fi; }
function pai { local e="allow from $2 to any port ${1/\// proto }";if [[ $4 ]];then nex "ufw $4 $e";else nex "ufw $e comment $3";fi; }
function pae { local e="allow $1"                                 ;if [[ $3 ]];then nex "ufw $3 $e";else nex "ufw $e comment $2";fi; }
function ple { local e="limit $1"                                 ;if [[ $3 ]];then nex "ufw $3 $e";else nex "ufw $e comment $2";fi; }
function sis { if [[ -f $1 ]];then sex "mv $1 $p17";swb "NEW $p18";touch $p05/vc_slash;cmw $p18 600 eth3;else swb "NO NEW $1";fi; }
function sni { case $1 in $inm5) printf $iip5;;$inm6) printf $iip6;;$znm1) printf $zip1;;$znm2) printf $zip2;;$znm3) printf $zip3;;$znm4) printf $zip4;;$vnm1) printf $vip1;;$vnm2) printf $vip2;;$vnm3) printf $vip3;;esac; }
function snc { if [[ ${1:0:3} = hrv ]];then printf ${1/[a-z]*-/}|tr -d '[aoel]';else case $1 in $vnm1) printf vpsl;;$vnm2) printf vpsm;;$vnm3) printf vpss;;esac;fi; }
function sjw { [[ $cunm = $inm5 || $cunm = $inm6 ]] || return;if [[ -d $p58 ]];then swn "JA EXISTE $p58/";else sex "mkdir -p $p58";cmw $p58 755 eth;fi;if [[ -f $p58/jwt ]];then swn "JA EXISTE $p58/jwt";else openssl rand -hex 32|tr -d '\n'|tee $p58/jwt 1>$p03;cmw $p58/jwt 444;fi;if [[ -f $p58/pubkeys ]];then swn "JA EXISTE $p58/pubkeys";else echo ${b[@]}|tr ' ' ',' > $p58/pubkeys;cmw $p58/pubkeys 400 eth2;fi; }
function unv { local f=${1:-23.1.0};curl -LO https://hyperledger.jfrog.io/artifactory/besu-binaries/besu/$f/besu-$f.tar.gz;sha256sum besu-$f.tar.gz;swn "INSTALAR BESU $f (SIM/nao)?";local rsp=nao;read rsp;if [[ $rsp = SIM ]];then tar xvf besu-$f.tar.gz;sex "cp -a besu-$f $p00/besu";sex "chown eth1:eth1 -R $p00/besu";cmw $p00/besu 755 eth1;fi; }
function gnv { local f="go${1:-1.20.5}.linux-amd64.tar.gz";swu "INSTALAR GO-LANG $f";cd $p02;sex "rm -f $f";wget -q https://go.dev/dl/$f;sex "rm -rf /usr/local/go";sex "tar -C /usr/local -xzf $f";echo 'if [ -d "/usr/local/go/bin" ];then PATH="$PATH:/usr/local/go/bin";fi' >> $p02/.profile; }
function mnv { local f="go/bin/mev-boost";swu 'INSTALAR MEV-BOOST';cd $p02;sex "rm -rf go";CGO_CFLAGS="-O -D__BLST_PORTABLE__" /usr/local/go/bin/go install github.com/flashbots/mev-boost@latest;sex "cp $f $p00";cmw $p00/mev-boost 755 eth4; }
function snv { local v=${1:-v2.7.0};local f="staking_deposit-cli-${2:-fdab65d}-linux-amd64.tar.gz";rm -f $f;curl -LO https://github.com/ethereum/staking-deposit-cli/releases/download/$v/$f;local s=$(sha256sum $f|cut -d' ' -f1);swn "INSTALAR $f ($s)?";local rsp=nao;read rsp;if [[ $rsp = $s ]];then tar xf $f --strip-components 2;fi; }
function dnv { local v=${1:-1.33.2};local f="ethdo-$v-linux-amd64.tar.gz";local e="https://github.com/wealdtech/ethdo/releases/download/v$v";rm -f $f $f.sha256;curl -LO $e/$f -LO $e/$f.sha256;local s=$(sha256sum $f|cut -d' ' -f1);local r=$(cat $f.sha256);if [[ $r = $s ]];then tar xf $f;swb "INSTALADO $f";fi; }
function gtv { local f="geth-linux-amd64-${1:-1.13.8}-${2:-b20b4a71}";rm -rf $f*;curl -LO https://gethstore.blob.core.windows.net/builds/$f.tar.gz;local s=$(md5sum $f.tar.gz|cut -d' ' -f1);swn "\nINSTALAR $f ($s)?";local rsp=nao;read rsp;if [[ $rsp = $s ]];then tar xf $f.tar.gz;sex "cp $f/geth $p00";cmw $p00/geth 755 eth;fi; }
function imk { local f="$p02/key.txt";echo $K > $f;$p00/lighthouse --datadir $p05 account validator import --network mainnet --reuse-password --password-file $f --directory $p19;rm -f $f; }
