#!/bin/bash

source /home/eth/eth2/t1

# cria link para tarefas
[[ -x $p0/eth2/t ]] || ln -s $p0/eth2/t6 $p0/eth2/t

if [[ $(echo $H|sudo -S ufw status 2>$s3|grep -i inactive) ]]; then
  echo -e "${i}INIT FIREWALL${f}"
  sudo ufw default deny incoming
  sudo ufw default allow outgoing
  sudo ufw deny 22/tcp comment oldssh
  sudo ufw deny 53 comment dns
  # sudo ufw allow 43/tcp comment whois
  # sudo ufw allow 123 comment ntp
  sudo ufw deny 30303 comment eth1
  sudo ufw deny 32400 comment plex
  sudo ufw deny 51413 comment torrent
  sudo ufw deny 9000 comment eth2
  sudo ufw deny 8545 comment geapi
  sudo ufw deny 5052 comment bnapi
  sudo ufw deny 5064 comment vcmet
  sudo ufw deny 9090/tcp comment prometheus
  sudo ufw deny 3000/tcp comment grafana
  sudo ufw allow 2020/tcp comment newssh
  sudo ufw enable
  sudo ufw status numbered
  echo -e "${i}ROOTKIT SCANNER${f}"
  sudo apt install -y chkrootkit
  sudo pip3 install speedtest-cli
  sudo chkrootkit  -q
else
  echo -e "${i}FIREWALL $(echo $H|sudo -S ufw status 2>$s3|grep -i status|tr '[:lower:]' '[:upper:]')${f}"
fi

if [[ -f $s4/$ethg.service || -f $s4/$ethb.service || -f $s4/$ethv.service ]]; then
  echo -e "${i}SERVER JA INSTALADO ANTES - LINUX UPDATE & SYSTEM CONFIGS SKIPPED${f}"
else
  echo -e "${i}UPDATE LINUX${f}"
  if [[ $(echo $H|sudo -S snap list 2>$s3) ]]; then
    sudo snap remove lxd
    sudo snap remove core18
    sudo snap remove snapd
    sudo apt purge snapd
  fi
  t4update linux

  echo -e "${i}UNATTENDED UPGRADES${f}"
  sudo apt install unattended-upgrades apt-listchanges landscape-common update-notifier-common python3-pip net-tools -y
  sudo dpkg-reconfigure -plow unattended-upgrades

  echo -e "${i}LINUX SYSTEM CONFIGS${f}"
  sudo timedatectl set-ntp on
  if [[ $cust = hrv ]]; then
    sudo timedatectl set-timezone Europe/Lisbon
    sed -e 's%^ *#NTP=.*$%NTP="ntp02.oal.ul.pt ntp04.oal.ul.pt time.google.com time.cloudflare.com time.facebook.com"%i' /etc/systemd/timesyncd.conf > ~/timesyncd.save
    sed -e 's%^ *ENABLED=.*$%ENABLED=0%i' /etc/default/motd-news > ~/motd-new.save
    sed -e 's%-wait-online *$%-wait-online --ignore=enp2s0 --ignore=wlo1%i' /lib/systemd/system/systemd-networkd-wait-online.service > ~/snwo.save
    sed -e 's%^.*UseDNS *=.*$%UseDNS=false%i' /etc/systemd/networkd.conf > ~/ntwd.save;echo 'UseDNS=false' >> ~/ntwd.save
    sudo mv ~/motd-new.save /etc/default/motd-news
    sudo mv ~/snwo.save /lib/systemd/system/systemd-networkd-wait-online.service
    sudo mv ~/ntwd.save /etc/systemd/networkd.conf
    sudo chown root:root /etc/default/motd-news
    sudo chown root:root /lib/systemd/system/systemd-networkd-wait-online.service
    sudo chown root:root /etc/systemd/networkd.conf
    sudo chmod 644 /etc/default/motd-news
    sudo chmod 644 /lib/systemd/system/systemd-networkd-wait-online.service
    sudo chmod 644 /etc/systemd/networkd.conf
  else
    sudo timedatectl set-timezone Europe/Berlin
    sed -e 's%^ *#NTP=.*$%NTP="time.google.com time.cloudflare.com time.facebook.com"%i' /etc/systemd/timesyncd.conf > ~/timesyncd.save
  fi
  sed -e 's%^ */* *Unattended-Upgrade::Mail .*$%Unattended-Upgrade::Mail "hernanilr@gmail.com";%i' /etc/apt/apt.conf.d/50unattended-upgrades > ~/t5-upg.save
  sed -e 's%^ *printf%# printf%i' /etc/update-motd.d/00-header > ~/t0-hea.save
  sed -e 's%^ *printf%# printf%i' /etc/update-motd.d/10-help-text > ~/t1-hel.save
  echo 'printf "Welcome to %s %s (%s %s %s)\n" "$(uname -n|cut -d. -f1)" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"' >> ~/t0-hea.save
  sudo mv ~/timesyncd.save /etc/systemd/timesyncd.conf
  sudo mv ~/t0-hea.save /etc/update-motd.d/00-header
  sudo mv ~/t1-hel.save /etc/update-motd.d/10-help-text
  sudo mv ~/t5-upg.save /etc/apt/apt.conf.d/50unattended-upgrades
  sudo chown root:root /etc/systemd/timesyncd.conf
  sudo chown root:root /etc/apt/apt.conf.d/*
  sudo chown root:root /etc/update-motd.d/*
  sudo chmod 644 /etc/systemd/timesyncd.conf
  sudo chmod 644 /etc/apt/apt.conf.d/*
  sudo chmod 755 /etc/update-motd.d/*
  # nao executa - nao acho ser necessario
  [[ -f /etc/update-motd.d/97-overlayroot ]] && sudo chmod -x /etc/update-motd.d/97-overlayroot
  sudo netplan apply
  sudo $sctl restart systemd-resolved
  sudo $sctl restart systemd-timesyncd
fi

if [[ $cunm != $znm1 && $cunm != $vnm1 ]]; then
  echo -e "${i}GETH & OPEN ETHEREUM NAO DEVE SER INSTALADOS AQUI - DEVE FAZER REBOOT${f}"
else
  user="eth1"
  if ! id $user &>$s3;then sudo useradd --no-create-home --shell /bin/false $user;fi
  if [[ -f $s4/$ethg.service ]]; then
    echo -e "${i}GETH JA INSTALADO${f}"
  else
    echo -e "${i}INSTALAR GETH${f}"
    golb="/var/lib/goethereum"
    if [[ $B = mainnet ]]; then
      blkc=''
      cach=4096 # default full node
      cach=1024 # default
      maxp=10
    else
      blkc=' --goerli'
      cach=1024 # default
      maxp=50   # default
    fi
    sudo add-apt-repository -y ppa:ethereum/ethereum
    sudo apt update -y
    sudo apt install -y software-properties-common geth
    sudo mkdir -p $golb
    sudo chown -R $user:$user $golb
    cat <<-EOF > $ethg.service
		[Unit]
		Description=eth1 geth service
		Wants=network-online.target
		After=network-online.target
		
		[Service]
		User=$user
		Group=$user
		Restart=always
		RestartSec=10
		ExecStart=$s0/geth$blkc --datadir $golb --http --http.addr $zip1 --maxpeers $maxp --cache $cach --ipcdisable
		ExecStopPost=$p0/eth2/t8mail GETHSTP \$SERVICE_RESULT \$EXIT_CODE \$EXIT_STATUS
		
		[Install]
		WantedBy=multi-user.target
		EOF
    sudo mv $ethg.service $s4/$ethg.service
    sudo chmod 644 $s4/$ethg.service
  fi
fi
