#!/bin/bash

i="\n\e[5m"
f="\e[25m\n"

meeu="$(whoami)"
user="eth2"

echo -e "${i}VAI COMPILAR LIGHT${f}"
if [ -x ~/.cargo/bin/rustup ]; then
  echo -e "${i}update rust${f}"
  source ~/.cargo/env
  rustup update
else
  sudo apt install -y git gcc g++ make cmake pkg-config libssl-dev
  echo -e "${i}install rust${f}"
  cd ~
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi
if [ -f ~/lighthouse/README.md ]; then
  cd ~/lighthouse
  git pull origin master
else
  sudo rm -rf ~/lighthouse
  cd ~
  git clone https://github.com/sigp/lighthouse.git
fi 
source ~/.cargo/env
cd ~/lighthouse
make
echo -e "${i}$(ntptime|grep -i ntp_|tr '[:lower:]' '[:upper:]')${f}"

if [ -x  ~/.cargo/bin/lighthouse ]; then

  blkc="--testnet medalla"
  dtdi="/var/lib/lighthouse"
  becn="$dtdi/beacon"
  vldt="$dtdi/validators"

  echo -e "${i}CONFIGURE BEACON${f} $H"
  if [ -f /etc/systemd/system/validator.service ]; then [ "$(sudo systemctl status validator|grep -i inactive)" ] || sudo systemctl stop validator;fi
  if [ -f /etc/systemd/system/beacon.service ];    then [ "$(sudo systemctl status beacon   |grep -i inactive)" ] || sudo systemctl stop beacon;fi
  cd ~
  sudo mkdir -p $becn
  if ! id $user &>/dev/null;then sudo useradd --no-create-home --shell /bin/false $user;fi
  sudo chown -R $user:$user $dtdi
  sudo cp ~/.cargo/bin/lighthouse /usr/local/bin
  sudo cat <<-EOF > beacon.service
  [Unit]
  Description=Lighthouse Beacon Node
  Wants=network-online.target
  After=network-online.target

  [Service]
  Type=simple
  User=$user
  Group=$user
  Restart=always
  RestartSec=5
  ExecStart=/usr/local/bin/lighthouse $blkc --datadir $dtdi bn --staking --eth1-endpoint $E --metrics

  [Install]
  WantedBy=multi-user.target
EOF
  sudo mv beacon.service /etc/systemd/system/beacon.service
  sudo ufw allow 9000 comment 'Lighthouse'
  sudo ufw reload
  sudo systemctl daemon-reload
  sudo systemctl start beacon
  sudo systemctl enable beacon
  sudo journalctl -f -u beacon.service

else

  echo -e "${i}NAO EXISTE BEACON COMPILADO PARA INSTALAR${f}"

fi
