#!/bin/bash

i="\n\e[5m"
f="\e[25m\n"

if [ -f ~/prysm/README.md ]; then

  echo -e "${i}JA COMPILOU PRYSM${f}"
  
else

  echo -e "${i}VAI COMPILAR LIGHT${f}"
  if [ -x ~/.cargo/bin/rustup ]; then
    echo -e "${i}update rust${f}"
    rustup update
  else
    sudo apt install -y git gcc g++ make cmake pkg-config libssl-dev
    echo -e "${i}install rust${f}"
    cd ~
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  fi
  if [ -f ~/lighthouse/README.md ]; then
    cd ~/lighthouse
    git pull origin master
  else
    sudo rm -rf ~/lighthouse
    cd ~
    git clone https://github.com/sigp/lighthouse.git
  fi 
  source ~/.cargo/env
  cd ~/lighthouse
  make
  echo -e "${i}$(ntptime|grep -i ntp_|tr '[:lower:]' '[:upper:]')${f}"

fi

