#!/bin/bash

i="\n\e[5m"
f="\e[25m\n"

meeu="$(whoami)"
user="eth2"
ethg="eth-geth"
ethb="eth-beacon"
ethv="eth-validator"
ethp="prometheus"
ethn="prometheus-node-exporter"
ethf="grafana-server"

if [ -x /usr/local/bin/lighthouse ]; then

  if [ "$B" = "mainnet" ]; then
    blkc=""
  else
    blkc="--testnet $B"
  fi
  dtdi="/var/lib/lighthouse"
  becn="$dtdi/beacon"
  vldt="$dtdi/validators"

  t6 vpr
  cd ~
  if [ -f $vldt/validator_definitions.yml ]; then
    echo -e "${i}\nCHAVES JA FORAM IMPORTADAS${F}"
  else
    if [ -d $HOME/$D ] && [ "$(ls -A $HOME/$D)" ]; then
      echo -e "${i}IMPORT VALIDATOR KEYS${f}"
      echo $H|sudo -S mkdir -p $dtdi 2>/dev/null
      sudo chown -R $meeu:$meeu $dtdi
      echo -e "STORE($K)\n"
      lighthouse $blkc --datadir $dtdi account validator import --directory $HOME/$D
      sudo chown -R $user:$user $dtdi
    else
      echo -e "${i}NAO EXISTE KEYS PARA IMPORTAR ($HOME/$D)${f}"
    fi
  fi

  echo -e "${i}CONFIGURE VALIDATOR${f}"
  cd ~
  echo $H|sudo -S mkdir -p $vldt 2>/dev/null
  sudo chown -R $user:$user $vldt
  cat <<-EOF > $ethv.service
  [Unit]
  Description=eth2 validator service
  Wants=network-online.target
  After=network-online.target

  [Service]
  User=$user
  Group=$user
  Restart=always
  RestartSec=10
  ExecStart=/usr/local/bin/lighthouse $blkc --datadir $dtdi vc

  [Install]
  WantedBy=multi-user.target
EOF
  sudo mv $ethv.service /etc/systemd/system/$ethv.service
  sudo chmod 644 /etc/systemd/system/$ethv.service
  t6 ve
  t6 va
  t6 vj

else

  echo -e "${i}NAO EXISTE BEACON INSTALADO - DEVE COMECAR POR AI${f}"
  
fi
