#!/bin/bash

i="\n\e[5m"
f="\e[25m\n"

meeu="$(whoami)"
user="eth2"

if [ -x /usr/local/bin/lighthouse ]; then

  blkc="--testnet medalla"
  dtdi="/var/lib/lighthouse"
  becn="$dtdi/beacon"
  vldt="$dtdi/validators"

  if [ -f /etc/systemd/system/validator.service ]; then [ "$(sudo systemctl status validator|grep -i inactive)" ] || sudo systemctl stop validator;fi
  if ! id $user &>/dev/null;then sudo useradd --no-create-home --shell /bin/false $user;fi
  cd ~
  if [ -f $vld/validator_definitions.yml ]; then
    echo -e "${i}\nCHAVES JA FORAM IMPORTADAS${F}"
  else
    echo -e "${i}IMPORT VALIDATOR WALLET${f}"
    sudo mkdir -p $vldt
    sudo chown -R $meeu:$meeu $dtdi
    echo -e "STORE($K)\n"
    lighthouse $blkc --datadir $dtdi account validator import --directory $HOME/$D
    sudo chown -R $user:$user $dtdi
  fi

  echo -e "${i}CONFIGURE VALIDATOR${f}"
  cd ~
  sudo mkdir -p $vldt
  sudo chown -R $user:$user $vldt
  sudo cat <<-EOF > validator.service
  [Unit]
  Description=Lighthouse Validator
  Wants=network-online.target
  After=network-online.target

  [Service]
  Type=simple
  User=$user
  Group=$user
  Restart=always
  RestartSec=5
  ExecStart=/usr/local/bin/lighthouse $blkc --datadir $dtdi vc

  [Install]
  WantedBy=multi-user.target
EOF
  sudo mv validator.service /etc/systemd/system/validator.service
  sudo systemctl daemon-reload
  sudo systemctl start validator
  sudo systemctl enable validator
  sudo journalctl -f -u validator.service

else

  echo -e "${i}NAO EXISTE BEACON INSTALADO - DEVE COMECAR POR AI${f}"
  
fi
