#!/bin/bash
# shellcheck disable=SC2053,SC2086

source /home/eth/eth2/t1

function hlp {
  local e=''
  e="$e\n$(basename $0) linux|reboot|besu [version]|geth [version] [commit]|mev [go version] [mev version]|cp\n"
  e="$e\n  net[vd]|lig[vd]\tupgrade nethermind v-version/d-database|lighthouse v-version/d-database"
  e="$e\n  mev\t\t\tupgrade mev-boost"
  e="$e\n  cp\t\t\tcopy & propagate  lighthouse"
  swn "$e"
}
function bck { [[ -f $p04/$1.service ]] || return;grep -q checkpoint-sync-url $p04/$1.service && return;cp $p04/$1.service $p02/$1.sav;sef "$e79" $p02/$1.sav > $p04/$1.service;nex $s00 daemon-reload; }

if [[ $1 = linux || $1 = reboot ]];then
  swb "FULL-UPGRADE >> ~/apt-t4$1.out";aex
  sudo apt update -y       2>&1 | sudo tee -a $p02/apt-t4$1.out >$p03
  sudo apt full-upgrade -y 2>&1 | sudo tee -a $p02/apt-t4$1.out >$p03
  sudo apt dist-upgrade -y 2>&1 | sudo tee -a $p02/apt-t4$1.out >$p03
  sudo apt autoremove   -y 2>&1 | sudo tee -a $p02/apt-t4$1.out >$p03
  sudo apt autoclean       2>&1 | sudo tee -a $p02/apt-t4$1.out >$p03
  sex chown $meeu:$meeu $p02/apt-t4$1.out
  [[ $1 = reboot ]] && { srb $p39 RB; }
fi
if [[ $1 = besu ]];then sex rm -fr $p00/besu.sav      ;sex mv $p00/besu      $p00/besu.sav       ;unv $2    ;fi
if [[ $1 = geth ]];then sex rm -f  $p00/geth.sav      ;sex mv $p00/geth      $p00/geth.sav       ;gtv $2 $3 ;fi
if [[ $1 = netv ]];then nnv D $2 $3;nnv S $2 $3;fi
if [[ $1 = netd ]];then t6 tgp;nex rm -rf $p07/nethermind_db/mainnet;nex rm -rf $p07/logs;t6 tea;touch $p50.lock;fi
if [[ $1 = ligd ]];then t6 bgp;nex rm -rf $p16/{blobs_db,chain_db,freezer_db};bck $s12   ;t6 bea;touch $p50.lock;fi
if [[ $1 = mev  ]];then sex rm -f  $p00/mev-boost.sav ;sex mv $p00/mev-boost $p00/mev-boost.sav  ;gnv $2;mnv $3;fi
[[ $1 = ligv || $1 = cp ]] || { [[ $1 ]] || hlp;exit; }
if [[ $1 = ligv && ($cunm = $znm4 || $cunm = $inm5 || $cunm = $vnm1 || $cunm = $vnm2) ]];then [[ -x $p02/.cargo/bin/rustup ]] && t6 ruv $3;t6 luc $2;fi
t6 lpi
