#!/bin/bash

i="\n\e[5m"
f="\e[25m\n"

echo -e "${i}FULL-UPGRADE${f}"
sudo apt update && sudo apt full-upgrade
echo -e "${i}DIST-UPGRADE${f}"
sudo apt dist-upgrade && sudo apt autoremove

if [ -x /usr/local/bin/lighthouse ]; then

  echo -e "${i}RUST UPDATE${f}"
  rustup update
  echo -e "${i}LIGHTHOUSE UPDATE${f}"
  if [ -f /etc/systemd/system/validator.service ]; then [ "$(sudo systemctl status validator|grep -i inactive)" ] || sudo systemctl stop validator;fi
  if [ -f /etc/systemd/system/beacon.service ];    then [ "$(sudo systemctl status beacon   |grep -i inactive)" ] || sudo systemctl stop beacon;fi
  cd ~/lighthouse
  git pull origin master
  make
  echo -e "\n$H\n"
  sudo mv /usr/local/bin/lighthouse /usr/local/bin/lighthouse.save
  sudo cp ~/.cargo/bin/lighthouse /usr/local/bin
  [ -f /etc/systemd/system/beacon.service ] && sudo systemctl start beacon
  [ -f /etc/systemd/system/validator.service ] && sudo systemctl start validator

else

  echo -e "${i}NAO EXISTE BEACON INSTALADO - DEVE COMECAR POR AI${f}"

fi
