#!/bin/bash

source /home/eth/eth2/t1

if [ "$1" = "linux" ] || [ "$1" = "reboot" ]; then
  echo -e "${i}FULL-UPGRADE${f}"
  [ "$1" = "reboot" ] && { t6 gpr; }
  echo $H|sudo -S apt update -y 2>/dev/null
  sudo apt full-upgrade -y && sudo apt dist-upgrade -y
  sudo apt autoremove -y
  sudo apt autoclean
  [ "$1" = "linux"  ] && { t6 ga; }
  [ "$1" = "reboot" ] && { sudo reboot; }
fi

if [ "$1" = "eth" ] && [ -x /usr/local/bin/lighthouse ]; then
  if [ "$cunm" = "$zon1" ] || [ "$cunm" = "$vpnl" ]; then
    if [ -x ~/.cargo/bin/rustup ]; then
      echo -e "${i}UPDATE RUST${f}"
      rustup update
    fi
    if [ -f ~/lighthouse/README.md ]; then
      cd ~/lighthouse
      make clean
      cargo clean
    else
      cd ~
      echo $H|sudo -S rm -rf ~/lighthouse 2>/dev/null
      git clone https://github.com/sigp/lighthouse.git
      cd ~/lighthouse
    fi 
    git fetch
    if [ "$(echo \"$2\"|egrep 'v[0-9]+\.[0-9]+\.[0-9]+')" ]; then
      v=$2
    else
      t=$(git rev-list --tags --max-count=1)
      v=$(git describe --tags $t)
    fi
    git checkout $v
    echo -e "${i}VAI COMPILAR LIGHT${f}"
    make
    if [ $? -eq 0  ] && [ -x  ~/.cargo/bin/lighthouse ]; then
      echo $H|sudo -S cp /usr/local/bin/lighthouse /usr/local/bin/lighthouse.save 2>/dev/null
      if [ "$bnip" != "$vcip" ]; then
        scp -P 2020 ~/.cargo/bin/lighthouse $vcip:~
        scp -P 2020 ~/.cargo/bin/lighthouse $vpsm:~
      fi
      echo $H|sudo -S cp ~/.cargo/bin/lighthouse /usr/local/bin 2>/dev/null
      t6 vpr
      t6 bpr
    else
      echo -e "${i}NAO EXISTE LIGHT COMPILADO PARA INSTALAR${f}"
    fi
  else
    if [ -x ~/lighthouse ]; then
      echo $H|sudo -S cp /usr/local/bin/lighthouse /usr/local/bin/lighthouse.save 2>/dev/null
      t6 vpr
      t6 bpr
      sudo mv ~/lighthouse /usr/local/bin
    else
      echo -e "${i}NAO EXISTE LIGHT COMPILADO PARA INSTALAR${f}"
    fi
  fi
  echo $H|sudo -S chmod 755 /usr/local/bin/lighthouse 2>/dev/null
  t6 ba
  t6 va
fi
