#!/bin/bash

source /home/eth/eth2/t1

if [[ $1 = linux || $1 = reboot || $1 = el ]];then
  swu 'FULL-UPGRADE'
  [[ $1 = reboot || $1 = el ]] && t6 gpr
  cex 'apt update -y'    ;sudo apt full-upgrade -y && sudo apt dist-upgrade -y
  cex 'apt autoremove -y';sudo apt autoclean
  [[ $1 = el     ]] && t6 gaj
  [[ $1 = reboot ]] && cex 'reboot'
fi
[[ $1 = cl || $1 = cp ]] || exit
if [[ $1 = cl && ($cunm = $znm1 || $cunm = $vnm1) ]];then
  [[ -x $p0/.cargo/bin/rustup ]] && { swu 'UPDATE RUST';rustup update stable; }
  if [[ -f $p0/lighthouse/README.md ]];then
    cd $p0/lighthouse;make clean;cargo clean                                                                                                                  # clean compile dirs
  else
    cd $p0;sex "rm -rf $p0/lighthouse";git clone https://github.com/sigp/lighthouse.git;cd $p0/lighthouse                                                     # get new git
  fi
  git fetch;if [[ $(echo $2|egrep 'v[0-9]+\.[0-9]+\.[0-9]+') ]];then v=$2;else t=$(git rev-list --tags --max-count=1);v=$(git describe --tags $t);fi
  git checkout $v;swu 'VAI COMPILAR LIGHT';make
  [[ $? -eq 0 && -x $p0/.cargo/bin/lighthouse ]] || swb 'ERRO COMPILAR ERRO'
fi
lwr                                                                                                                                                           # propagate & install lighthouse  
