#!/bin/bash

source /home/eth/eth2/t1

[[ $1 = usbstart   ]] && echo 1 > ${p[6]}
[[ $1 = usbstop    ]] && echo 0 > ${p[6]}
[[ $1 = cpunoturbo ]] && echo 1 > ${p[7]}
[[ $1 = cputurbo   ]] && echo 0 > ${p[7]}
[[ $1              ]] || { swn "USB_BUS10_ON $(cat ${p[6]})";swn "NO_TURBO_CPU $(cat ${p[7]})"; }
