#!/bin/bash

source /home/eth/eth2/t1

[[ $1 = usbstart   ]] && echo 1 > $p44
[[ $1 = usbstop    ]] && echo 0 > $p44
[[ $1 = cpunoturbo ]] && echo 1 > $p43
[[ $1 = cputurbo   ]] && echo 0 > $p43
[[ $1              ]] || { swn "USB_BUS10_ON $(cat $p44 2>$p03)";swn "NO_TURBO_CPU $(cat $p43 2>$p03)"; }
