#!/bin/bash

source ~/eth2/t1

petc="/etc/prometheus"

if [ "$cuip" = "$vcip" ]; then
  echo -e "${i}MONITOR NAO DEVE SER INSTALADO - DEVE FICAR ONDE FICA O BEACON${f}"
else
  if [ -f $petc/prometheus.yml ]; then
    echo -e "${i}PROMETHEUS JA INSTALADO${f}"
  else
    if [ "$bnip" != "$vcip" ];then vlcl="$vcip";else vlcl="127.0.0.1";fi
    echo -e "${i}CONFIGURE PROMETHEUS${f}"
    echo $H|sudo -S apt install -y prometheus prometheus-node-exporter 2>/dev/null
    t6 mpr
    cd ~
    cat <<-EOF > prometheus.yml
		global:
		  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
		  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
		  # Attach these labels to any time series or alerts when communicating with
		  # external systems (federation, remote storage, Alertmanager).
		  external_labels:
		    monitor: 'lighthouse-monitor'
		# A scrape configuration containing exactly one endpoint to scrape:
		# Here it's Prometheus itself.
		scrape_configs:
		  - job_name: 'node_exporter'
		    static_configs:
		      - targets: ['localhost:9100']
		  - job_name: 'nodes'
		    metrics_path: /metrics
		    static_configs:
		      - targets: ['localhost:5054']
		  - job_name: 'validators'
		    metrics_path: /metrics
		    static_configs:
		      - targets: ['$vlcl:5064']
		EOF
    sudo mv prometheus.yml $petc/prometheus.yml
    echo -e "${i}CONFIGURE GRAFANA${f}"
    wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
    sudo add-apt-repository -y "deb https://packages.grafana.com/oss/deb stable main"
    sudo apt update -y
    sudo apt install -y grafana
    t6 me
    t6 ma
  fi
  echo -e "\nConfigure Grafana Login admin:admin http://$(uname -n):3000 & Change password $V & DATASOURCE URL http://127.0.0.1:9090\n"
  echo -e "Import some dashboards from the dashboards directory in https://github.com/sigp/lighthouse-metrics"
  echo -e "In the Grafana UI, go to Dashboards -> Manage -> Import -> Upload .json file."
  echo -e "The Summary.json dashboard is a good place to start.\n"
fi
