#!/bin/bash

i="\n\e[5m"
f="\e[25m\n"

meeu="$(whoami)"
user="eth2"

echo -e "${i}WARNING: WARNING: THIS IS AN IRREVERSIBLE OPERATION${f}"
echo -e "${i}WARNING: WITHDRAWING STAKED ETH WILL NOT BE POSSIBLE UNTIL ETH1/ETH2 MERGE${f}"
echo -e "${i}Exit my validator${f}"
if [ -x /usr/local/bin/lighthouse ]; then

  blkc="--testnet medalla"
  wllt="/var/lib/lighthouse"
  golb="$wllt/validators"
  echo -e "${i}EXIT VALIDATORS${f}"
  if [ -f $golb/validator_definitions.yml ]; then
    echo -e "${i}STORE($K) WALLET($W)${f}"
    for kst in $(ls $golb/*.json)
    do echo lighthouse $blkc --datadir $wllt account validator exit --keystore $kst
    done
  else
    echo -e "${i}\nCHAVES AINDA NAO FORAM IMPORTADAS${f}"
  fi
  echo -e "${i}LIGTH: CONFIGURE VALIDATOR${f}"

else

  echo -e "${i}NAO EXISTEM VALIDATORS TO EXIT${f}"

fi
