#!/bin/bash

i="\n\e[5m"
f="\e[25m\n"

meeu="$(whoami)"
user="eth2"
blkc="--medalla"
plib="/var/lib/prometheus"
petc="/etc/prometheus"
verp="2.22.1" # prometheus
vern="1.0.1"  # node_exporter

echo -e "${i}Step 11 — Install Prometheus${f}"
echo "Confirmar ultimas versoes: prometheus ($verp), node_exporter ($vern) em https://prometheus.io/download"

sudo systemctl stop grafana-server
sudo systemctl stop node
sudo systemctl stop prometheus

cd ~
if ! id $user &>/dev/null;then sudo useradd --no-create-home --shell /bin/false $user;fi
sudo mkdir -p $petc
sudo mkdir -p $plib
sudo chown -R $user:$user $petc
sudo chown -R $user:$user $plib

curl -LO https://github.com/prometheus/prometheus/releases/download/v$verp/prometheus-$verp.linux-amd64.tar.gz
tar xvf prometheus-$verp.linux-amd64.tar.gz 
sudo cp prometheus-$verp.linux-amd64/prometheus /usr/local/bin
sudo cp prometheus-$verp.linux-amd64/promtool /usr/local/bin
sudo cp -r prometheus-$verp.linux-amd64/consoles $petc
sudo cp -r prometheus-$verp.linux-amd64/console_libraries $petc

sudo chown -R $user:$user /usr/local/bin/prometheus
sudo chown -R $user:$user /usr/local/bin/promtool 
sudo chown -R $user:$user $petc/consoles
sudo chown -R $user:$user $petc/console_libraries

rm -rf prometheus-$verp.linux-amd64.tar.gz prometheus-$verp.linux-amd64

# teste comando do servico
# sudo -u prometheus /usr/local/bin/prometheus --config.file $petc/prometheus.yml --storage.tsdb.path $plib/ --web.console.templates=$petc/consoles --web.console.libraries=$petc/console_libraries
# PARA LIGHT
  sudo cat <<-EOF > prometheus.yml
  global:
    scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    # scrape_timeout is set to the global default (10s).
  # Alertmanager configuration
  alerting:
    alertmanagers:
    - static_configs:
      - targets:
        # - alertmanager:9093
  # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
  rule_files:
    # - "first_rules.yml"
    # - "second_rules.yml"
  # A scrape configuration containing exactly one endpoint to scrape:
  # Here it's Prometheus itself.
  scrape_configs:
    - job_name: 'nodes'
      metrics_path: /metrics
      static_configs:
        - targets: ['localhost:5054']
    - job_name: 'node'
      static_configs:
        - targets: ['localhost:9100']
EOF
# PARA PRYSM
  sudo cat <<-EOF > prometheus.yml
  global:
    scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    # scrape_timeout is set to the global default (10s).
  # Alertmanager configuration
  alerting:
    alertmanagers:
    - static_configs:
      - targets:
        # - alertmanager:9093
  # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
  rule_files:
    # - "first_rules.yml"
    # - "second_rules.yml"
  # A scrape configuration containing exactly one endpoint to scrape:
  # Here it's Prometheus itself.
  scrape_configs:
    - job_name: 'validator'
      static_configs:
        - targets: ['localhost:8081']
    - job_name: 'beacon'
      static_configs:
        - targets: ['localhost:8080']
    - job_name: 'node'
      static_configs:
        - targets: ['localhost:9100']
EOF

sudo cat << EOF > prometheus.service
[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=$user
Group=$user
Restart=always
RestartSec=5
ExecStart=/usr/local/bin/prometheus --config.file $petc/prometheus.yml --storage.tsdb.path $plib/ --web.console.templates=$petc/consoles --web.console.libraries=$petc/console_libraries

[Install]
WantedBy=multi-user.target
EOF
sudo mv prometheus.service /etc/systemd/system/prometheus.service
[ -f prometheus.yml ] && sudo mv prometheus.yml $petc/prometheus.yml
sudo chown $user:$user $petc/prometheus.yml

echo -e "\nStep 12 — Install Node Exporter"
if ! id $user &>/dev/null;then sudo useradd --no-create-home --shell /bin/false $user;fi
curl -LO https://github.com/prometheus/node_exporter/releases/download/v$vern/node_exporter-$vern.linux-amd64.tar.gz
tar xvf node_exporter-$vern.linux-amd64.tar.gz 
sudo cp node_exporter-$vern.linux-amd64/node_exporter /usr/local/bin
sudo chown -R $user:$user /usr/local/bin/node_exporter
rm -rf node_exporter-$vern.linux-amd64.tar.gz node_exporter-$vern.linux-amd64

sudo cat << EOF > node.service
[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=$user
Group=$user
Type=simple
ExecStart=/usr/local/bin/node_exporter

[Install]
WantedBy=multi-user.target
EOF
sudo mv node.service /etc/systemd/system/node.service

echo -e "${i}Step 13 — Install Grafana${f}"
wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
sudo apt update
apt-cache policy grafana
sudo apt install grafana
sudo ufw allow 3000/tcp comment 'Grafana'
sudo ufw reload

sudo systemctl daemon-reload
sudo systemctl start prometheus
sudo systemctl start node
sudo systemctl start grafana-server
sudo systemctl enable prometheus
sudo systemctl enable node
sudo systemctl enable grafana-server

echo -e "\nConfigure Grafana Login admin:admin http://$(uname -n):3000"
