#!/bin/bash

source /home/eth/eth2/t1

sau eth4;gnv $1;mnv                                                                                                                                           # install go-lang & mev-boost
rlys="$rlys,https://0x9000009807ed12c1f08bf4e81c6da3ba8e3fc3d953898ce0102433094e5f22f21102ec057841fcb81978ed1ea0fa8246@builder-relay-mainnet.blocknative.com" # dead
rlys="$rlys,https://0xb0b07cd0abef743db4260b0ed50619cf6ad4d82064cb4fbec9d3ec530f7c5e6793d9f286c4e082c0244ffb9f2658fe88@bloxroute.regulated.blxrbdn.com"       # rv errors
rlys="$rlys,https://0xa44f64faca0209764461b2abfe3533f9f6ed1d51844974e22d79d4cfd06eff858bb434d063e512ce55a1841e66977bfd@proof-relay.ponrelay.com"              # rv errors
rlys="$rlys,https://0x8c7d33605ecef85403f8b7289c8058f440cbb6bf72b055dfe2f3e2c6695b6a1ea5a9cd0eb3a7982927a463feb4c3dae2@relay.wenmerge.com"                    # rv errors
rlys="$rlys,https://0x98650451ba02064f7b000f5768cf0cf4d4e492317d82871bdc87ef841a0743f69f0f1eea11168503240ac35d101c9135@mainnet-relay.securerpc.com"           # low market share
rlys="$rlys,https://0xb3ee7afcf27f1f1259ac1787876318c6584ee353097a50ed84f51a1f21a323b3736f271a895c7ce918c038e4265918be@relay.edennetwork.io"                  # low market share
rlys="$rlys,https://0x8c4ed5e24fe5c6ae21018437bde147693f68cda427cd1122cf20819c30eda7ed74f72dece09bb313f2a1855595ab677d@regional.titanrelay.xyz"               # OFAC sanctioned

rlys="https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money"
rlys="$rlys,https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net"
rlys="$rlys,https://0xa7ab7a996c8584251c8f925da3170bdfd6ebc75d50f5ddc4050a6fdc77f2a3b5fce2cc750d0865e05d7228af97d69561@agnostic-relay.net"
rlys="$rlys,https://0xa15b52576bcbf1072f4a011c0f99f9fb6c66f3e1ff321f11f461d15e31b1cb359caa092c71bbded0bae5b5ea401aab7e@aestus.live"
rlys="$rlys,https://0x8c4ed5e24fe5c6ae21018437bde147693f68cda427cd1122cf20819c30eda7ed74f72dece09bb313f2a1855595ab677d@global.titanrelay.xyz"
rlys="$rlys,https://0x8b5d2e73e2a3a55c6c87b8b6eb92e0149a125c852751db1422fa951e42a09b82c142c3ea98d0d9930b056a3bc9896b8f@bloxroute.max-profit.blxrbdn.com"

epmv="-addr $(sni $cunm):18550"                                                                                                                               # listen  address           default localhost:18550
epmv="$epmv -request-timeout-getheader 950"                                                                                                                   # timeout getHeader         default 950
epmv="$epmv -request-timeout-getpayload 4000"                                                                                                                 # timeout getPayload        default 4000
epmv="$epmv -request-timeout-regval 6500"                                                                                                                     # timeout registerValidator default 3000
epmv="$epmv -min-bid 0.005"                                                                                                                                   # minimum bid to accept from a relay
epmv="$epmv -relay-check -relays $rlys"
cd
cat <<-EOF > $s14.service
[Unit]
Description=mev-boost service
Wants=network-online.target
After=network-online.target

[Service]
User=eth4
Group=eth4
Restart=always
RestartSec=60
TimeoutStopSec=600
RuntimeMaxSec=infinity
ExecStart=$p00/mev-boost -mainnet -log-no-version $epmv
ExecStopPost=+$p02/eth2/t7 MEVBSTP \$SERVICE_RESULT \$EXIT_CODE \$EXIT_STATUS

[Install]
WantedBy=multi-user.target
EOF
sex "mv $s14.service $p04";cmw $p04/$s14.service 644
swn 'para iniciar mev-boost: t mea'
