#!/bin/bash

source /home/eth/eth2/t1

if [[ $cunm = $znm1 || $cunm = $znm4 || $cunm = $vnm1 ]];then                                                                                                 # ec here
  alow="192.168.8.25,192.168.8.31,192.168.8.34"
  epec=" --miner-enabled=true --miner-coinbase=\"${p[99]}\" --engine-jwt-secret=${p[37]}/data/jwt"                                                            # MERGE
  epec=" --engine-jwt-secret=${p[37]}/data/jwt --host-allowlist=$alow --engine-host-allowlist=$alow"                                                          # MERGE
  maxp=25    # default
  pp2p=30303 # default
  swu 'INSTALAR BESU';sex "mkdir -p ${p[37]}/data"
  sex "tar -xvzf besu-22.7.1.tar.gz -C ${p[37]}";sex "mv ${p[37]}/besu-* ${p[37]}/besu"                                                                       # get besu binaries
  sex "chown eth1:eth1 -R ${p[37]}/besu";cmw ${p[37]} 755 eth1;cmw ${p[37]}/besu 755 eth1;cmw ${p[37]}/data 700 eth1                                          # set owner/permissions
  cat <<-EOF > ${p[87]}.service
	[Unit]
	Description=besu service
	Wants=network-online.target
	After=network-online.target
	
	[Service]
	User=eth1
	Group=eth1
	Restart=always
	RestartSec=10
	ExecStart=${p[37]}/besu/bin/besu --data-path=${p[37]}/data --sync-mode=X_SNAP --data-storage-format=BONSAI --pruning-enabled --p2p-port=$pp2p --rpc-http-enabled --rpc-http-host=$zip1 --max-peers=$maxp$epec
	ExecStopPost=${p[9]}/eth2/t8mail BESUSTP \$SERVICE_RESULT \$EXIT_CODE \$EXIT_STATUS
	
	[Install]
	WantedBy=multi-user.target
	EOF
  sex "cp ${p[18]}/geth/jwt ${p[37]}/data";cmw ${p[37]}/data/jwt 600 eth1 
  sex "mv ${p[87]}.service $(pjp 4 87).service";cmw $(pjp 4 87).service 644
fi
swn 'sudo netplan apply'
swn 'AND reboot'
swn 'para iniciar ec: t6 jwt;t gea'
