#!/bin/bash

source /home/eth/eth2/t1

if [[ $cunm = $znm1 || $cunm = $znm4 || $cunm = $vnm1 ]];then                                                                                                 # ec here
  vuel='22.7.1'                                                                                                                                               # besu version
  alow='192.168.8.25,192.168.8.31,192.168.8.34'                                                                                                               # my servers
  maxp=25    # default
  pp2p=30303 # default
  epec="--miner-enabled=true --miner-coinbase=\"${p[99]}\""                                                                                                   # coincashew guide had these NOT USING
  epec="--sync-mode=X_SNAP --data-storage-format=BONSAI --pruning-enabled=true"                                                                               # recommend snap sync/bonsai/pruning
  epec="$epec --p2p-port=$pp2p --rpc-http-enabled=true --rpc-http-host=$zip1"                                                                                 # enable  rpc:8545
  epec="$epec --rpc-http-cors-origins=all"                                                                                                                    # eliminate CORS errors
  epec="$epec --max-peers=$maxp"                                                                                                                              # set p2p connections
  epec="$epec --engine-jwt-secret=${p[37]}/data/jwt --host-allowlist=$alow --engine-host-allowlist=$alow"                                                     # MERGE
  swu 'INSTALAR BESU';sex "mkdir -p ${p[37]}/data"
  tar xvf besu-$vuel.tar.gz;sex "cp -a besu-$vuel ${p[0]}/besu"                                                                                               # install besu binaries
  sex "chown eth1:eth1 -R ${p[0]}/besu";cmw ${p[0]}/besu 755 eth1;cmw ${p[37]} 755 eth1;cmw ${p[37]}/data 700 eth1                                            # set owner/permissions
  cat <<-EOF > ${p[87]}.service
	[Unit]
	Description=besu service
	Wants=network-online.target
	After=network-online.target
	
	[Service]
	User=eth1
	Group=eth1
	Restart=always
	RestartSec=10
	ExecStart=${p[0]}/besu/bin/besu --data-path=${p[37]}/data $epec
	ExecStopPost=${p[9]}/eth2/t8mail BESUSTP \$SERVICE_RESULT \$EXIT_CODE \$EXIT_STATUS
	
	[Install]
	WantedBy=multi-user.target
	EOF
  sex "cp ${p[18]}/geth/jwt ${p[37]}/data";cmw ${p[37]}/data/jwt 600 eth1 
  sex "mv ${p[87]}.service $(pjp 4 87).service";cmw $(pjp 4 87).service 644
fi
swn 'sudo netplan apply'
swn 'AND reboot'
swn 'para iniciar ec: t6 jwt;t gea'
