#!/bin/bash

source /home/eth/eth2/t1

function jva { local f=$(basename $1);cp $1 $f.sav;cp $1 $f.new;echo -e "$2" >> $f.new;sex "cp $f.new $1"; }                                                  # add lines to end file

if [[ $cunm = $znm1 || $cunm = $znm4 || $cunm = $vnm1 ]];then                                                                                                 # ec here
  swu 'INSTALAR BESU';sex 'apt install default-jdk libjemalloc-dev -y';jva ${p[36]} "${p[88]}";cmw ${p[36]} 644 root                                          # besu execution client needs
  sex "mkdir -p ${p[37]}/data";sau eth1;cmw ${p[37]} 755 eth1;cmw ${p[37]}/data 700 eth1                                                                      # create dir & user for ec
  unv                                                                                                                                                         # download/install besu binaries
  alow='192.168.8.25,192.168.8.31,192.168.8.34'                                                                                                               # my servers
  maxp=25    # default
  pp2p=30303 # default
  epec="--miner-enabled=true --miner-coinbase=\"${p[99]}\""                                                                                                   # coincashew guide had these NOT USING
  # Aug 26 16:23:43 hrv-zotac3 lighthouse[271300]: Aug 26 15:23:43.003 ERRO Error during execution engine upcheck   error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(192.168.8.25)), port: Some(8551), path: "/", query: None, fragment: None }, source: TimedOut }), service: exec
  epec="--pruning-enabled=true"                                                                                                                               # DO NOT REMOVE but pruning deprecated for bonsai tries
  epec="--sync-mode=X_SNAP --data-storage-format=BONSAI --pruning-enabled=true"                                                                               # recommend snap sync/bonsai/pruning
  epec="$epec --p2p-port=$pp2p --rpc-http-enabled=true --rpc-http-host=$zip1"                                                                                 # enable  rpc:8545
  eped="$eped --rpc-http-cors-origins=chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn"                                                                    # for metamask
  epec="$epec --max-peers=$maxp"                                                                                                                              # set p2p connections
  epec="$epec --engine-jwt-secret=${p[37]}/data/jwt --host-allowlist=$alow --engine-host-allowlist=$alow"                                                     # MERGE
  cat <<-EOF > ${p[87]}.service
	[Unit]
	Description=besu service
	Wants=network-online.target
	After=network-online.target
	
	[Service]
	User=eth1
	Group=eth1
	Restart=always
	RestartSec=10
	ExecStart=${p[0]}/besu/bin/besu --data-path=${p[37]}/data $epec
	ExecStopPost=${p[9]}/eth2/t8mail BESUSTP \$SERVICE_RESULT \$EXIT_CODE \$EXIT_STATUS
	
	[Install]
	WantedBy=multi-user.target
	EOF
  if [[ -f jwt ]];then sex "cp jwt ${p[37]}/data";fi;if [[ -f ${p[18]}/geth/jwt ]];then sex "cp ${p[18]}/geth/jwt ${p[37]}/data";fi
  if [[ -f ${p[37]}/data/jwt ]];then cmw ${p[37]}/data/jwt 600 eth1;else swb "needs ${p[37]}/data/jwt secret";fi
  sex "mv ${p[87]}.service $(pjp 4 87).service";cmw $(pjp 4 87).service 644
fi
swn 'sudo netplan apply'
swn 'AND reboot'
swn 'para iniciar ec: t6 jwt;t gea'
