#!/bin/bash

source /home/eth/eth2/t1

swu 'INSTALAR GETH';sex "mkdir -p $p08/geth";sau eth1;if [[ -f jwt ]];then sjw eth1 $p08/geth;else swb "needs $p08/geth/jwt";fi;cmw $p08 755 eth1;cmw $p08/geth 700 eth1
gtv $1 $2
maxp=10                                                                                                                                                     # default
pp2p=30303                                                                                                                                                  # default
othe="--http.corsdomain 'chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn' --http.vhosts '*'"                                                            # for metamask
othe=''
othe="$othe --cache 16384"
othe="$othe --state.scheme=path"                                                                                                                            # full pruning historical states
cat <<-EOF > $s10.service
[Unit]
Description=geth service
Wants=network-online.target
After=network-online.target

[Service]
User=eth1
Group=eth1
Restart=always
RestartSec=10
TimeoutStopSec=300
ExecStart=$p00/geth --datadir $p08 --mainnet --port $pp2p --http --http.addr $iip5 --maxpeers $maxp --authrpc.addr $iip5 --authrpc.jwtsecret $p08/geth/jwt$othe
PermissionsStartOnly=true
ExecStopPost=$p02/eth2/t7 GETHSTP \$SERVICE_RESULT \$EXIT_CODE \$EXIT_STATUS

[Install]
WantedBy=multi-user.target
EOF
sex "mv $s10.service $p04";cmw $p04/$s10.service 644
