#!/bin/bash

source /home/eth/eth2/t1

sau eth4;gnv $1;mnv                                                                                                                                           # install go-lang & mev-boost
rlys='https://0x8b5d2e73e2a3a55c6c87b8b6eb92e0149a125c852751db1422fa951e42a09b82c142c3ea98d0d9930b056a3bc9896b8f@bloxroute.max-profit.blxrbdn.com'
rlys="$rlys,https://0x98650451ba02064f7b000f5768cf0cf4d4e492317d82871bdc87ef841a0743f69f0f1eea11168503240ac35d101c9135@mainnet-relay.securerpc.com"
rlys="$rlys,https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net"
rlys="$rlys,https://0x9000009807ed12c1f08bf4e81c6da3ba8e3fc3d953898ce0102433094e5f22f21102ec057841fcb81978ed1ea0fa8246@builder-relay-mainnet.blocknative.com"
rlys="$rlys,https://0xb3ee7afcf27f1f1259ac1787876318c6584ee353097a50ed84f51a1f21a323b3736f271a895c7ce918c038e4265918be@relay.edennetwork.io"
rlys="$rlys,https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money"
rlys="$rlys,https://0xa7ab7a996c8584251c8f925da3170bdfd6ebc75d50f5ddc4050a6fdc77f2a3b5fce2cc750d0865e05d7228af97d69561@agnostic-relay.net"
rlys="$rlys,https://0xa15b52576bcbf1072f4a011c0f99f9fb6c66f3e1ff321f11f461d15e31b1cb359caa092c71bbded0bae5b5ea401aab7e@aestus.live"
# rlys="$rlys,https://0x84e78cb2ad883861c9eeeb7d1b22a8e02332637448f84144e245d20dff1eb97d7abdde96d4e7f80934e5554e11915c56@relayooor.wtf"
trgh=950                                                                                                                                                      # timeout getHeader         default 950
trgp=4000                                                                                                                                                     # timeout getPayload        default 4000
trrv=3000                                                                                                                                                     # timeout registerValidator default 3000
mbid=0.02                                                                                                                                                     # minimum bid to accept from a relay
epmv="-addr $zip1:18550"                                                                                                                                      # listen-address default "localhost:18550"
epmv="$epmv -request-timeout-getheader $trgh"
epmv="$epmv -request-timeout-getpayload $trgp"
epmv="$epmv -request-timeout-regval $trrv"
epmv="$epmv -relay-check -relays $rlys"
epmv="$epmv -min-bid $mbid"
cat <<-EOF > $s14.service
[Unit]
Description=mev-boost service
Wants=network-online.target
After=network-online.target

[Service]
User=eth4
Group=eth4
Restart=always
RestartSec=10
ExecStart=$p00/mev-boost -mainnet -log-no-version $epmv
PermissionsStartOnly=true
ExecStopPost=$p02/eth2/t7 MEVBSTP \$SERVICE_RESULT \$EXIT_CODE \$EXIT_STATUS

[Install]
WantedBy=multi-user.target
EOF
sex "mv $s14.service $p04";cmw $p04/$s14.service 644
swn 'para iniciar mev-boost: t mea'
