#!/bin/bash

source /home/eth/eth2/t1

swu 'INSTALAR NETHERMIND';sex 'apt libsnappy-dev libc6-dev libc6 unzip -y';sex "mkdir -p $p61";sau eth1;sjw;cmw $p61 755 eth1
nnv $1 $2
maxp=20
pp2p=30303;i1t || pp2p=30304
othe=''
othe="$othe --Sync.AncientBodiesBarrier 11052984 --Sync.AncientReceiptsBarrier 11052984"
apip='127.0.0.1'
if [[ $cunm = $inm5 ]];then apip="$iip5";else apip="$iip6";fi
cat <<-EOF > $s44.service
[Unit]
Description=Nethermind Execution Client
Wants=network-online.target
After=network-online.target

[Service]
User=eth1
Group=eth1
Restart=always
RestartSec=60
TimeoutStopSec=600
WorkingDirectory=$p61
Environment="DOTNET_BUNDLE_EXTRACT_BASE_DIR=$p61"
ExecStart=$p00/nethermind/nethermind --config mainnet --datadir $p61 --Network.P2PPort $pp2p -JsonRpc.Enabled true --JsonRpc.Host $apip -JsonRpc.EngineHost $apip --JsonRpc.EnginePort 8551 --JsonRpc.JwtSecretFile $p58/jwt --Network.MaxActivePeers $maxp --Sync.SnapSync true$othe
ExecStopPost=+$p02/eth2/t7 GETHSTP \$SERVICE_RESULT \$EXIT_CODE \$EXIT_STATUS

[Install]
WantedBy=multi-user.target
EOF
sex "mv $s44.service $p04";cmw $p04/$s44.service 644
