#!/bin/bash

source /home/eth/eth2/t1

swu 'WARNING: WARNING: THIS IS AN IRREVERSIBLE OPERATION'
swu 'WARNING: WITHDRAWING STAKED ETH WILL NOT BE POSSIBLE UNTIL THE MERGE'
swu 'WARNING: TO ENTER AGAIN YOU GO TO A LONG QUEUE'
swu 'QUER MESMO EXIT MY VALIDATORS?';read rsp
if [[ $rsp = sim && ! -f $p05/vc_slash && ! -f $p05/vc_lock && -f $p05/vc_keys && -x $p00/lighthouse ]];then
  swu 'EXIT VALIDATORS'
  if [[ -f $p17/validator_definitions.yml ]];then
    swn "STORE($K) WALLET($W)";for kst in $(ls $p17/*.json);do swn "$p00/lighthouse --datadir $p05 account validator exit --keystore $kst";done
  else
    swu '\nCHAVES AINDA NAO FORAM IMPORTADAS'
  fi
  swu 'LIGTH: CONFIGURE VALIDATOR'
else
  swu 'NAO EXISTEM VALIDATORS TO EXIT'
fi
