#!/bin/bash

source /home/eth/eth2/t1

function tve { local f='';echo;for f in $(ls $p19/key*.json 2>$p03);do echo $(basename $f);done;echo;swn 'QUER MESMO SAIR ESTES VALIDATORS (SIM/nao)?';read rsp;if [[ $rsp = SIM ]];then return;else return 1;fi; }
function lve { [[ -d $p19 && $(ls $p19/key*.json 2>$p03) ]] && tve && { echo;swn "STORE($K) EXIT-PHRASE(Exit my validator)";echo;local f='';for f in $(ls $p19/key*.json 2>$p03);do echo $p00/lighthouse --datadir $p05 account validator exit --keystore $f --beacon-node http://$zip4:5052;done; }; }
function eve {
  [[ -x $p02/ethdo     ]] || { dnv                              ; }
  [[ -x $p02/ethdo     ]] || { swb 'TEM DE TER ETHDO'    ;return; }
  [[ -d $p19 && $(ls $p19/key*.json 2>$p03) ]] && tve && { local f='';for f in $(ls $p19/key*.json 2>$p03);do echo $p02/ethdo $s27 validator exit --validator=$f --passphrase="$K";done; }
}

[[ $1 = eve ]] && { eve; }
[[ $1 = lve ]] && { lve; }

if [[ ! $1 ]];then
  m=''
  m="$m\neve\t\tvoluntary exit\t(ethdo)"
  m="$m\nlve\t\tvoluntary exit\t(lighthouse)"
  swn "$m\n"
fi
