#!/bin/bash

source ~/eth2/t1

if [ "$(uname -n)" = "hrv-zen" ]; then
  cli="eth2.0-deposit-cli/validator_keys"
  bs1="/media/eth/cs1"
  bs2="/media/eth/cs2"
  cs1="$bs1/validator_keys"
  cs2="$bs2/validator_keys"
  lng="spanish"
  if [ "$B" = "mainnet" ];then nmv=18;else nmv=3;fi 
  if [ -d ~/$D ] && [ "$(ls -A ~/$D)" ]; then
    echo -e "${i}CHAVES ESTAO PRONTAS${f}"
  elif [ -d ~/$cli ] && [ "$(ls -A ~/$cli)" ]; then
    if [ -d $bs1 ]; then
      if  [ -d $cs1 ]; then
        echo -e "${i}ARQUIVO OFFLINE $cs1 JA EXISTE${f}"
      else
        cp -R ~/$cli $cs1
        sudo chown -R eu:eu $cs1
        sudo chmod 755 $cs1
        sudo chmod 644 $cs1/*
      fi
    else
      echo -e "${i}ARQUIVO OFFLINE $bs1 NAO ESTA MONTADO${f}"
    fi
    if [ -d $bs2 ]; then
      if  [ -d $cs2 ]; then
        echo -e "${i}ARQUIVO OFFLINE $cs2 JA EXISTE${f}"
      else
        cp -R ~/$cli $cs2
        sudo chown -R eu:eu $cs2
        sudo chmod 755 $cs2
        sudo chmod 644 $cs2/*
      fi
    else
      echo -e "${i}ARQUIVO OFFLINE $bs2 NAO ESTA MONTADO${f}"
    fi
    cp -R ~/$cli ~
    echo -e "${i}CHAVES FORAM ARQUIVADAS - VERIFICAR AQUIVO OFFLINE${f}"
  elif [ -f ~/eth2.0-deposit-cli/README.md ]; then
    cd ~/eth2.0-deposit-cli
    echo -e "${i}PARA GERAR $nmv NOVAS CHAVES CHAIN $B${f}"
    echo -e "STORE($K)"
    echo -e "${i}PARA GERAR $nmv NOVAS CHAVES CHAIN $B${f}"
    # if keystores lost to recover keys use ./deposit.sh existing-mnemonic
    ./deposit.sh new-mnemonic --num_validators $nmv --mnemonic_language $lng --chain $B
    echo -e "${i}para ARQUIVAR CHAVES executar de novo - OFFLINE & com USB INSTALADOS${f}"
  else
    echo -e "${i}INSTALAR SCRIPT CHAVES${f}"
    sudo apt install -y python3-pip python3-testresources git
    cd ~
    git clone https://github.com/ethereum/eth2.0-deposit-cli.git
    cd ~/eth2.0-deposit-cli
    sudo ./deposit.sh install
    echo -e "${i}para GERAR CHAVES executar de novo - OFFLINE${f}"
  fi
else
  echo -e "${i}TEM DE ESTAR HOME${f}"
fi
