#!/bin/bash

source /home/eth/eth2/t1

if [[ $cunm != $mavc ]];then
  swn "MONITOR NAO DEVE SER INSTALADO AQUI - DEVE FICAR EM $mavc"
else
  if [[ -f ${p[2]}/${p[74]}.yml ]];then
    swu 'PROMETHEUS JA INSTALADO'
  else
    swu 'CONFIGURE PROMETHEUS'
    cex "apt install ${p[74]} ${p[74]}-node-exporter -y"
    t6 fpr;t6 npr;t6 ppr
    cd ${p[9]}
    cat <<-EOF > ${p[74]}.yml
		global:
		  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
		  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
		  # Attach these labels to any time series or alerts when communicating with
		  # external systems (federation, remote storage, Alertmanager).
		  external_labels:
		    monitor: 'lighthouse-monitor'
		# A scrape configuration containing exactly one endpoint to scrape:
		# Here it's Prometheus itself.
		scrape_configs:
		  - job_name: 'node_exporter'
		    static_configs:
		      - targets: ['localhost:9100']
		  - job_name: 'nodes'
		    metrics_path: /metrics
		    static_configs:
		      - targets: ['localhost:5054']
		  - job_name: 'validators'
		    metrics_path: /metrics
		    static_configs:
		      - targets: ['$vip3:5064', 'localhost:5064']
		EOF
    sex "mv ${p[74]}.yml $(pjp 2 74).yml"
    swu 'CONFIGURE GRAFANA'
    wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
    sudo add-apt-repository -y 'deb https://packages.grafana.com/oss/deb stable main'
    cex 'apt update -y'
    cex 'apt install grafana -y'
    t6 pe;t6 ne;t6 fe
    t6 pa;t6 na;t6 fa
  fi
  swn "\nConfigure Grafana Login admin:admin http://$(uname -n):3000 & Change password $V & DATASOURCE URL http://127.0.0.1:9090\n"
  swn 'Import some dashboards from the dashboards directory in https://github.com/sigp/lighthouse-metrics'
  swn 'In the Grafana UI, go to Dashboards -> Manage -> Import -> Upload .json file.'
  swn 'The Summary.json dashboard is a good place to start.\n'
fi
